### PR TITLE
Projects: Fix ACP delete, Update issues.

### LINKED ISSUE #962: V3: Project: Revisit the Project Module resources
Buggy Scenarios in Project Terraform Resource

1️⃣ User removal from Project not detected

**Current behavior:**
```
user_reference_list is Optional + Computed TypeSet.
When the user removes a block from HCL (e.g., removes a user from user_reference_list), Terraform does not detect a change:
Result → provider never clears the user in the API call → user remains in the project.
```

**Root cause:**
```
Terraform SDK doesn’t consider removal a change when the field is Optional + Computed.
Computed state keeps the old value even if user removes the block in HCL.
```

2️⃣ **Access Control Policy (ACP) removal not handled correctly**

**Current behavior:**
```
When a user removes an ACP from the config, Terraform provider does not send Operation: Delete in the API payload. As a result, the ACP is not removed from the project.
```

Code:
```
resource "nutanix_project" "projects" {
  name          = "project name gullapalli test 4"
  description   = "project description"
  use_project_internal = true
  api_version = "3.1"
  
  cluster_reference_list {
    kind = "cluster"
    uuid = local.cluster0
  }

  account_reference_list {
    kind = "account"
    uuid = "733dde4b-a6c8-4502-aeeb-94a6907c6f70"
  }

  subnet_reference_list {
    kind = "subnet"
    uuid = "bbc8b989-2d99-463f-b6c9-d4932171a4af"
  }

  default_subnet_reference {
    kind = "subnet"
    uuid = "bbc8b989-2d99-463f-b6c9-d4932171a4af"
  }
  
  user_reference_list{
    name= "ssptest1@qa.nucalm.io"
    kind= "user"
    uuid= "fa769725-98e3-5bcd-b2cc-1759213807bd"
  }
  acp{
    name = "acp_project_admin_35b7e35f-77e5-4d89-779b-e7785952f792"
    role_reference{
      kind= "role"
      uuid= "25b7e35f-77e5-4d89-779b-e7785952f792"
      name="Project Admin"
    }
    user_reference_list{
      name= "ssptest1@qa.nucalm.io"
      kind= "user"
      uuid= "fa769725-98e3-5bcd-b2cc-1759213807bd"
    }
  }

  cluster_uuid = local.cluster0
}

```

### LINKED ISSUE #1042: Projects: ACP: Order changes in API response lead to data inconsistency in state file.
User Config:
```
# Project Admin ACP
  acp {
    role_reference {
      kind = "role"
      uuid = "d563d49e-7717-4113-64ba-1f8051050f5f"
      name = "Project Admin"
    }
    user_reference_list {
      name = "ssptest1@qa.nucalm.io"
      kind = "user"
      uuid = "fa769725-98e3-5bcd-b2cc-1759213807bd"
    }
    # user_reference_list {
    #   name = "dnd_approval_1@qa.nucalm.io"
    #   kind = "user"
    #   uuid = "17207671-39a1-5018-9f28-2d1e7583d324"
    # }
  }

  # # Developer ACP
  acp {
    role_reference {
      kind = "role"
      uuid = "e7bf85d2-f667-4074-40ae-a8e4aa3d1987"
      name = "Developer"
    }
    user_reference_list {
      name = "ssptest2@qa.nucalm.io"
      kind = "user"
      uuid = "ac79343f-4b5d-58fc-b40a-984fdc6847d6"
    }
    # user_group_reference_list {
    #   kind= "user_group"
    #   name= "cn=dnd_approval_group_1,cn=users,dc=qa,dc=nucalm,dc=io"
    #   uuid= "39834df6-4bf2-561b-bb3f-f520d7b12650"
    # }
  }
```

State file
```
User set Project Admin first and then Developer next. In state file, for first entity user reference is shown as ssptest1 but it should be ssptset2(Config itended it to be Developer user. -- Solved.
 "role_reference": [
                  {
                    "kind": "role",
                    "name": "Developer",
                    "uuid": "e7bf85d2-f667-4074-40ae-a8e4aa3d1987"
                  }
                ],
                "user_group_reference_list": [],
                "user_reference_list": [
                  {
                    "kind": "user",
                    "name": "ssptest1@qa.nucalm.io",
                    "uuid": "fa769725-98e3-5bcd-b2cc-1759213807bd"
                  }
                ]

"role_reference": [
    {
      "kind": "role",
      "name": "Project Admin",
      "uuid": "d563d49e-7717-4113-64ba-1f8051050f5f"
    }
  ],
  "user_group_reference_list": [],
  "user_reference_list": [
    {
      "kind": "user",
      "name": "ssptest2@qa.nucalm.io",
      "uuid": "ac79343f-4b5d-58fc-b40a-984fdc6847d6"
    }
  ]
}
```

### LINKED ISSUE #1043: Project: ACP: Adding a new user or new user group to existing ACP is failed.
Add a user or User group to existing ACP of project is failed.

Example: User Config during create
```
resource "nutanix_project" "projects" {
  name                 = "terraform debug 11"
  description          = "project description"
  use_project_internal = true
  api_version          = "3.1"

  cluster_reference_list {
    kind = "cluster"
    uuid = local.cluster_ext_id
  }

  account_reference_list {
    kind = "account"
    uuid = "f94cdeaf-d7ea-4cf4-b29f-6cbf117bd594"
  }

  subnet_reference_list {
    kind = "subnet"
    uuid = data.nutanix_subnets_v2.subnet.subnets[0].ext_id
  }

  default_subnet_reference {
    kind = "subnet"
    uuid = data.nutanix_subnets_v2.subnet.subnets[0].ext_id
  }

  # # # Project Admin User
  user_reference_list {
    name = "ssptest1@qa.nucalm.io"
    kind = "user"
    uuid = "fa769725-98e3-5bcd-b2cc-1759213807bd"
  }

  # # # Developer User
  user_reference_list {
    name = "ssptest2@qa.nucalm.io"
    kind = "user"
    uuid = "ac79343f-4b5d-58fc-b40a-984fdc6847d6"
  }

  # user_reference_list {
  #   name = "dnd_approval_1@qa.nucalm.io"
  #   kind = "user"
  #   uuid = "17207671-39a1-5018-9f28-2d1e7583d324"
  # }

  # external_user_group_reference_list {
  #   kind= "user_group"
  #   name= "cn=dnd_approval_group_1,cn=users,dc=qa,dc=nucalm,dc=io"
  #   uuid= "39834df6-4bf2-561b-bb3f-f520d7b12650"
  # }

  # Project Admin ACP
  acp {
    role_reference {
      kind = "role"
      uuid = "d563d49e-7717-4113-64ba-1f8051050f5f"
      name = "Project Admin"
    }
    user_reference_list {
      name = "ssptest1@qa.nucalm.io"
      kind = "user"
      uuid = "fa769725-98e3-5bcd-b2cc-1759213807bd"
    }
    # user_reference_list {
    #   name = "dnd_approval_1@qa.nucalm.io"
    #   kind = "user"
    #   uuid = "17207671-39a1-5018-9f28-2d1e7583d324"
    # }
  }

  # # Developer ACP
  acp {
    role_reference {
      kind = "role"
      uuid = "e7bf85d2-f667-4074-40ae-a8e4aa3d1987"
      name = "Developer"
    }
    user_reference_list {
      name = "ssptest2@qa.nucalm.io"
      kind = "user"
      uuid = "ac79343f-4b5d-58fc-b40a-984fdc6847d6"
    }
    # user_group_reference_list {
    #   kind= "user_group"
    #   name= "cn=dnd_approval_group_1,cn=users,dc=qa,dc=nucalm,dc=io"
    #   uuid= "39834df6-4bf2-561b-bb3f-f520d7b12650"
    # }
  }

  cluster_uuid = local.cluster_ext_id
}

```

During Update: user added a new user under Project Admin role
```
resource "nutanix_project" "projects" {
  name                 = "terraform debug 11"
  description          = "project description"
  use_project_internal = true
  api_version          = "3.1"

  cluster_reference_list {
    kind = "cluster"
    uuid = local.cluster_ext_id
  }

  account_reference_list {
    kind = "account"
    uuid = "f94cdeaf-d7ea-4cf4-b29f-6cbf117bd594"
  }

  subnet_reference_list {
    kind = "subnet"
    uuid = data.nutanix_subnets_v2.subnet.subnets[0].ext_id
  }

  default_subnet_reference {
    kind = "subnet"
    uuid = data.nutanix_subnets_v2.subnet.subnets[0].ext_id
  }

  # # # Project Admin User
  user_reference_list {
    name = "ssptest1@qa.nucalm.io"
    kind = "user"
    uuid = "fa769725-98e3-5bcd-b2cc-1759213807bd"
  }

  # # # Developer User
  user_reference_list {
    name = "ssptest2@qa.nucalm.io"
    kind = "user"
    uuid = "ac79343f-4b5d-58fc-b40a-984fdc6847d6"
  }

  user_reference_list {
    name = "dnd_approval_1@qa.nucalm.io"
    kind = "user"
    uuid = "17207671-39a1-5018-9f28-2d1e7583d324"
  }

  # external_user_group_reference_list {
  #   kind= "user_group"
  #   name= "cn=dnd_approval_group_1,cn=users,dc=qa,dc=nucalm,dc=io"
  #   uuid= "39834df6-4bf2-561b-bb3f-f520d7b12650"
  # }

  # Project Admin ACP
  acp {
    role_reference {
      kind = "role"
      uuid = "d563d49e-7717-4113-64ba-1f8051050f5f"
      name = "Project Admin"
    }
    user_reference_list {
      name = "ssptest1@qa.nucalm.io"
      kind = "user"
      uuid = "fa769725-98e3-5bcd-b2cc-1759213807bd"
    }
    user_reference_list {
      name = "dnd_approval_1@qa.nucalm.io"
      kind = "user"
      uuid = "17207671-39a1-5018-9f28-2d1e7583d324"
    }
  }

  # # Developer ACP
  acp {
    role_reference {
      kind = "role"
      uuid = "e7bf85d2-f667-4074-40ae-a8e4aa3d1987"
      name = "Developer"
    }
    user_reference_list {
      name = "ssptest2@qa.nucalm.io"
      kind = "user"
      uuid = "ac79343f-4b5d-58fc-b40a-984fdc6847d6"
    }
    # user_group_reference_list {
    #   kind= "user_group"
    #   name= "cn=dnd_approval_group_1,cn=users,dc=qa,dc=nucalm,dc=io"
    #   uuid= "39834df6-4bf2-561b-bb3f-f520d7b12650"
    # }
  }

  cluster_uuid = local.cluster_ext_id
}

```

### PR DESCRIPTION
**Pull request by GullapalliAkhil**

### CODE REVIEW

File: nutanix/services/prism/resource_nutanix_project.go [hunk 1]
```diff
@@ -1719,12 +1731,36 @@ func expandCreateAcp(pr []interface{}, d *schema.ResourceData, projectUUID strin
...
+					}
+					acpRes.UserReferenceList = refList
+				}
 			}
 
+			// Handle multiple user groups in user_group_reference_list (TypeSet)
 			if v1, ok := v["user_group_reference_list"]; ok {
-				acpRes.UserGroupReferenceList = validateArrayRef(v1.(*schema.Set), utils.StringPtr("user_group"))
+				if groupSet, ok := v1.(*schema.Set); ok && groupSet.Len() > 0 {
+					groupRefs := groupSet.List()
```
Comment (GullapalliAkhil) [inline nutanix/services/prism/resource_nutanix_project.go:1775]: We can add this code in common function.

**Comment by Haroon-Dweikat-Ntx** [comment]
/ok-to-test -p prism
- 🧪 **`Build Status: `** `failure`
- 📌 **`GitHub Action: `** [View GitHub Actions Run](https://github.com/nutanix/terraform-provider-nutanix/actions/runs/20809431760)
- 📊 **`Code Coverage: `** `Current line coverage (49.6) is below threshold (50). Kindly add more acceptance tests.`
- 📝 **`Test Summary: `**
```txt
==================================================🧪 TEST SUMMARY 🧪=================================================================================
Total Test Cases Run 🚀: 37
Total Test Cases Passed ✅: 29 (78 %)
Total Test Cases Failed ❌: 1 (2 %)
Total Test Cases Skipped ⚠️: 7 (18 %)
==================================================================================================================================================

================================================== TESTS SUCCEEDED ✅ =============================================================================

✅ TestResourceNutanixCategoriesteUpgradeV0
✅ TestFilters_replaceFilterPrefixes
✅ TestExpandStringList
✅ TestExpandStringListEmptyItems
✅ TestAccNutanixAssertHelperDS
✅ TestAccNutanixCategoryKeyDataSource_basic
✅ TestAccNutanixCategoryKeyDataSource_withValues
✅ TestAccNutanixProjectDataSourceByID_basic
✅ TestAccNutanixProjectDataSourceByName_basic
✅ TestAccNutanixRecoveryPlanDataSourceConfig_WithID
✅ TestAccNutanixRecoveryPlanDataSourceConfig_WithName
✅ TestAccNutanixAccessControlPolicy_WithUser
✅ TestAccNutanixAccessControlPolicy_WithCluster
✅ TestAccNutanixAccessControlPolicy_WithVPC
✅ TestAccNutanixAccessControlPolicy_WithConnectivityType
✅ TestAccNutanixCategoryKey_basic
✅ TestAccNutanixCategoryKey_update
✅ TestAccNutanixCategoryValue_basic
✅ TestAccNutanixCategoryValue_update
✅ TestAccNutanixProject_basic
✅ TestAccNutanixProject_withInternal
✅ TestAccNutanixProject_withInternalUpdate
✅ TestAccNutanixProject_withInternalWithACP
✅ TestAccNutanixProject_withInternalWithACPUserGroup
✅ TestAccNutanixRecoveryPlanWithStageList_basic
✅ TestAccNutanixRecoveryPlanWithStageListDynamic_basic
✅ TestAccNutanixRecoveryPlansDataSource_basic
✅ TestAccNutanixProjectsDataSource_basic
✅ TestAccNutanixRecoveryPlanWithStageList_importBasic
===================================================================================================================================================

================================================== TESTS FAILED ❌ ================================================================================

❌ TestAccNutanixProject_importBasic
===================================================================================================================================================

================================================== TESTS SKIPPED ⚠️ ==============================================================================
⚠️ TestAccNutanixProtectionRuleDataSource_basic   : Reason: ➡️ :      data_source_protection_rule_test.go:15: 
⚠️ TestAccNutanixProtectionRulesDataSource_basic   : Reason: ➡️ :      data_source_protection_rules_test.go:14: 
⚠️ TestAccNutanixAccessControlPolicy_basic   : Reason: ➡️ :      resource_nutanix_access_control_policy_test.go:20: 
⚠️ TestAccNutanixAccessControlPolicy_WithCategory   : Reason: ➡️ :      resource_nutanix_access_control_policy_test.go:95: 
⚠️ TestAccNutanixProtectionRule_basic   : Reason: ➡️ :      resource_nutanix_protection_rule_test.go:19: 
⚠️ TestAccResourceNutanixProtectionRule_importBasic   : Reason: ➡️ :      resource_nutanix_protection_rule_test.go:60: 
⚠️ TestAccNutanixRecoveryPlanWithNetwork_basic   : Reason: ➡️ :      resource_nutanix_recovery_plan_test.go:112: 
===================================================================================================================================================

```

**Review by abhinavbansal29 — APPROVED** [review]
