### PR TITLE
Fix #73 Added datasource of subnets

### LINKED ISSUE #73: Cannot use nutanix_subnets data source
**Describe the bug**
Cannot use nutanix_subnets datasource using a simple configuration
```
provider "nutanix" {
  username = "admin"
  password = "password"
  endpoint = "its-prism-central-lab"
  insecure = true
  port = 9440
  wait_timeout = 10
  //Optional
}
data "nutanix_clusters" "clusters" {
}
data "nutanix_subnets" "subnets" {
}
```

**Expected behavior**
terraform plan running without errors

**Logs**
```
➜  terraform terraform plan

Error: Invalid data source

  on main.tf line 43, in data "nutanix_subnets" "subnets":
  43: data "nutanix_subnets" "subnets" {

The provider provider.nutanix does not support data source "nutanix_subnets".
```

**Versions (please complete the following information):**
 - OS 
```
OSX ➜  10.14.5
```
 - Terraform
```
Terraform v0.12.4
+ provider.nutanix (unversioned)
```
 - Nutanix Cluster
``` 
5.10.5
```
 - Nutanix Prism Central
```
5.10.5
```
 - Terraform provider version (using posted RC1? Compiling yourself? If so, from Develop or Master, and what commit id?
```
commit b22b01e704a7009f45676a0af662f58a31a78832 (HEAD -> tf-0.12-suppport, origin/tf-0.12-suppport)
Author: Marin Salinas <marinssalinas@gmail.com>
Date:   Wed Jul 17 12:22:01 2019 -0500
```

### PR DESCRIPTION
**Pull request by coderGo93**
Fix for #73 
- Added data source of subnets (`nutanix_subnets`)
- Added testacc for data source of subnets
- Added subnets in provider

### CODE REVIEW

File: nutanix/data_source_nutanix_subnets.go [hunk 1]
```diff
@@ -0,0 +1,748 @@
...
+
+	"github.com/hashicorp/terraform/helper/schema"
+	"github.com/terraform-providers/terraform-provider-nutanix/utils"
+)
+
+func dataSourceNutanixSubnets() *schema.Resource {
+	return &schema.Resource{
+		Read:          dataSourceNutanixSubnetsRead,
+		SchemaVersion: 1,
+		StateUpgraders: []schema.StateUpgrader{
```
Comment (marinsalinas) [inline nutanix/data_source_nutanix_subnets.go]: Please remove the schema upgraders

File: nutanix/data_source_nutanix_subnets.go [hunk 2]
```diff
@@ -0,0 +1,748 @@
...
+
+	return nil
+}
+
+func resourceDatasourceSubnetsStateUpgradeV0(is map[string]interface{}, meta interface{}) (map[string]interface{}, error) {
+	log.Printf("[DEBUG] Entering resourceDatasourceSubnetStateUpgradeV0")
+	return resourceNutanixCategoriesMigrateState(is, meta)
+}
+
+func resourceNutanixDatasourceSubnetsResourceV0() *schema.Resource {
```
Comment (marinsalinas) [inline nutanix/data_source_nutanix_subnets.go]: please remove this.

File: nutanix/data_source_nutanix_subnets.go [hunk 3]
```diff
@@ -0,0 +1,748 @@
...
+	if err := d.Set("entities", entities); err != nil {
+		return err
+	}
+
+	d.SetId(resource.UniqueId())
+
+	return nil
+}
+
+func resourceDatasourceSubnetsStateUpgradeV0(is map[string]interface{}, meta interface{}) (map[string]interface{}, error) {
```
Comment (marinsalinas) [inline nutanix/data_source_nutanix_subnets.go]: please remove this.

**Review by marinsalinas — CHANGES_REQUESTED** [review]

File: nutanix/data_source_nutanix_subnets.go (hunk 1 above)
Comment (coderGo93) [reply nutanix/data_source_nutanix_subnets.go]: Ok, i'll remove, thank you marin

File: nutanix/data_source_nutanix_subnets.go (hunk 3 above)
Comment (coderGo93) [reply nutanix/data_source_nutanix_subnets.go]: done

File: nutanix/data_source_nutanix_subnets.go (hunk 2 above)
Comment (coderGo93) [reply nutanix/data_source_nutanix_subnets.go]: done, thank you marin

File: nutanix/data_source_nutanix_subnets.go [hunk 4]
```diff
@@ -0,0 +1,477 @@
...
+	"github.com/hashicorp/terraform/helper/schema"
+	v3 "github.com/terraform-providers/terraform-provider-nutanix/client/v3"
+	"github.com/terraform-providers/terraform-provider-nutanix/utils"
+)
+
+func dataSourceNutanixSubnets() *schema.Resource {
+	return &schema.Resource{
+		Read:          dataSourceNutanixSubnetsRead,
+		SchemaVersion: 1,
+		Schema: map[string]*schema.Schema{
```
Comment (marinsalinas) [inline nutanix/data_source_nutanix_subnets.go:13]: could you add a input as optional, let's say name?

I think we already have in master a way to get subnets by name, it would be nice if we can add it.

**Review by marinsalinas — CHANGES_REQUESTED** [review]

**Comment by marinsalinas** [comment]
Also please rebase from master to update this branch and run the tests again.

File: go.sum [hunk 5]
```diff
@@ -879,8 +879,11 @@ github.com/xiang90/probing v0.0.0-20160813154853-07dd2e8dfe18/go.mod h1:UETIi67q
 github.com/xiang90/probing v0.0.0-20190116061207-43a291ad63a2/go.mod h1:UETIi67q53MR2AWcXfiuqkDkRtnGDLqkBTpCHuJHxtU=
 github.com/xlab/treeprint v0.0.0-20161029104018-1d6e34225557 h1:Jpn2j6wHkC9wJv5iMfJhKqrZJx3TahFx+7sbZ7zQdxs=
 github.com/xlab/treeprint v0.0.0-20161029104018-1d6e34225557/go.mod h1:ce1O1j6UtZfjr22oyGxGLbauSBp2YVXpARAosm7dHBg=
+<<<<<<< HEAD
```
Comment (marinsalinas) [inline go.sum]: Rebase leftover, please fix it.

File: go.sum [hunk 6]
```diff
@@ -879,8 +879,11 @@ github.com/xiang90/probing v0.0.0-20160813154853-07dd2e8dfe18/go.mod h1:UETIi67q
...
 github.com/xordataexchange/crypt v0.0.3-0.20170626215501-b2862e3d0a77/go.mod h1:aYKd//L2LvnjZzWKhF00oedf4jCCReLcmhLdhm1A27Q=
 github.com/yuin/goldmark v1.1.25/go.mod h1:3hX8gzYuyVAZsxl0MRgGTJEmQBFcNTphYh9decYSb74=
+=======
```
Comment (marinsalinas) [inline go.sum]: leftover

File: go.sum [hunk 7]
```diff
@@ -879,8 +879,11 @@ github.com/xiang90/probing v0.0.0-20160813154853-07dd2e8dfe18/go.mod h1:UETIi67q
...
+>>>>>>> chore: updated vendor with a new import of tools goimports
```
Comment (marinsalinas) [inline go.sum]: leftover

File: go.sum [hunk 8]
```diff
@@ -922,9 +925,15 @@ golang.org/x/crypto v0.0.0-20190222235706-ffb98f73852f/go.mod h1:6SG95UA2DQfeDnf
 golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2/go.mod h1:djNgcEr1/C05ACkg1iLfiJU5Ep61QUkGW8qpdssI0+w=
 golang.org/x/crypto v0.0.0-20190426145343-a29dc8fdc734 h1:p/H982KKEjUnLJkM3tt/LemDnOc1GiZL5FCVlORJ5zo=
 golang.org/x/crypto v0.0.0-20190426145343-a29dc8fdc734/go.mod h1:yigFU9vqHzYiE8UmvKecakEJjdnWj3jj499lnFckfCI=
+<<<<<<< HEAD
```
Comment (marinsalinas) [inline go.sum]: leftover

File: nutanix/data_source_nutanix_subnets.go [hunk 9]
```diff
@@ -0,0 +1,477 @@
...
+	"github.com/hashicorp/terraform/helper/resource"
+	"github.com/hashicorp/terraform/helper/schema"
+	v3 "github.com/terraform-providers/terraform-provider-nutanix/client/v3"
+	"github.com/terraform-providers/terraform-provider-nutanix/utils"
+)
+
+func dataSourceNutanixSubnets() *schema.Resource {
+	return &schema.Resource{
+		Read:          dataSourceNutanixSubnetsRead,
+		SchemaVersion: 1,
```
Comment (marinsalinas) [inline nutanix/data_source_nutanix_subnets.go]: Remove this schema version.

**Review by marinsalinas — CHANGES_REQUESTED** [review]

File: go.sum (hunk 5 above)
Comment (coderGo93) [reply go.sum]: deleted it, thank you so much

File: go.sum (hunk 6 above)
Comment (coderGo93) [reply go.sum]: deleted it, thank you so much

File: go.sum (hunk 7 above)
Comment (coderGo93) [reply go.sum]: deleted it, thank you so much

File: go.sum (hunk 8 above)
Comment (coderGo93) [reply go.sum]: deleted it, thank you so much

File: nutanix/data_source_nutanix_subnets.go (hunk 9 above)
Comment (coderGo93) [reply nutanix/data_source_nutanix_subnets.go]: deleted it, thank you so much

**Review by marinsalinas — APPROVED** [review]
LGTM!
