### PR TITLE
Fix for issue 58

### LINKED ISSUE #58: Unable to create vm using guest_customization_cloud_init_custom_key_values
**Describe the bug**
Unable to create a vm using guest_customization_cloud_init_custom_key_values 

**Expected behavior**
Able to create the vm with the attribute guest_customization_cloud_init_custom_key_values like below,
`guest_customization_cloud_init_custom_key_values = {
  "username" = "centos1"
  "password" = "nutanix/4u"
  
}
`

**Logs**
`panic: interface conversion: interface {} is map[string]interface {}, not map[string]string
2019-05-07T17:30:55.845+1000 [DEBUG] plugin.terraform-provider-nutanix_v1.0.1_x4:
2019-05-07T17:30:55.845+1000 [DEBUG] plugin.terraform-provider-nutanix_v1.0.1_x4: goroutine 84 [running]:
2019-05-07T17:30:55.845+1000 [DEBUG] plugin.terraform-provider-nutanix_v1.0.1_x4: github.com/terraform-providers/terraform-provider-nutanix/nutanix.getVMResources(0xc00036d810, 0xc000131110, 0x1ad85da, 0x2)
2019-05-07T17:30:55.845+1000 [DEBUG] plugin.terraform-provider-nutanix_v1.0.1_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-nutanix/nutanix/resource_nutanix_virtual_machine.go:1465 +0x17bf
2019-05-07T17:30:55.845+1000 [DEBUG] plugin.terraform-provider-nutanix_v1.0.1_x4: github.com/terraform-providers/terraform-provider-nutanix/nutanix.resourceNutanixVirtualMachineCreate(0xc00036d810, 0x192aae0, 0xc0005b2b00, 0x24, 0x2416700)
2019-05-07T17:30:55.845+1000 [DEBUG] plugin.terraform-provider-nutanix_v1.0.1_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-nutanix/nutanix/resource_nutanix_virtual_machine.go:774 +0x446
2019-05-07T17:30:55.845+1000 [DEBUG] plugin.terraform-provider-nutanix_v1.0.1_x4: github.com/terraform-providers/terraform-provider-nutanix/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc000510bd0, 0xc000358730, 0xc0003febe0, 0x192aae0, 0xc0005b2b00, 0x100b601, 0xc00034fb80, 0x10bdcdc)
2019-05-07T17:30:55.845+1000 [DEBUG] plugin.terraform-provider-nutanix_v1.0.1_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-nutanix/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:225 +0x351`

**Versions (please complete the following information):**
 - Mojave OSX 
 - Terraform - v0.11.13
 - PE AOS 5.10.1, PC - 5.10.1.1
- Terraform provider version v1.0.1

### PR DESCRIPTION
**Pull request by yannickstruyf3**
error when using guest_customization_cloud_init_custom_key_values
closes #58

### CODE REVIEW

File: nutanix/resource_nutanix_virtual_machine.go [hunk 1]
```diff
@@ -1938,3 +1941,11 @@ func CountDiskListCdrom(dl []*v3.VMDisk) (int, error) {
 	}
 	return counter, nil
 }
+
+func ConvertMapString(o map[string]interface{}) map[string]string {
```
Comment (marinsalinas) [inline nutanix/resource_nutanix_virtual_machine.go]: Can you move this function into ./utils/utils.go

**Review by marinsalinas — CHANGES_REQUESTED** [review]
All great, just move the function into utils.

**Review by marinsalinas — APPROVED** [review]
LGTM Thanks!
