### PR TITLE
fix nutanix_image version

### LINKED ISSUE #682: nutanix_image version always shows changes
### Nutanix Cluster Information

 - Nutanix Cluster (Prism Element / AOS) 6.5.5.7
 - Nutanix Prism Central: Version pc.2024.1.0.1

### Terraform Version

Terraform v1.9.0
on darwin_arm64
+ provider registry.terraform.io/nutanix/nutanix v1.9.5

### Affected Resource(s)

* nutanix_image

### Terraform Configuration Files

```hcl
resource "nutanix_image" "rocky9" {
  name        = "Rocky9"
  description = "Public Rocky9 Base Image sourced from https://dl.rockylinux.org/pub/rocky/9/images/x86_64/${var.rocky9_image_name}"
  source_uri  = "https://dl.rockylinux.org/pub/rocky/9/images/x86_64/${var.rocky9_image_name}"
  checksum = {
    checksum_algorithm = "SHA_256"
    checksum_value     = var.rocky9_image_checksum
  }
  version = {
    product_name    = "Rocky9"
    product_version = var.rocky9_image_name
  }
}
```

### Issue
With the above code, everytime we run terraform it always shows changes to the "version" even though its not being changed.

It should say no changes.

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # nutanix_image.rocky9 will be updated in-place
  ~ resource "nutanix_image" "rocky9" {
        id                             = "fefc7ecd-050d-463e-a14b-e96d2e6c62b2"
        name                           = "Rocky9"
      ~ version                        = {
          + "product_name"    = "Rocky9"
          + "product_version" = "Rocky-9-GenericCloud-LVM-9.4-20240609.0.x86_64.qcow2"
        }
        # (12 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### PR DESCRIPTION
**Pull request by Haroon-Dweikat-Ntx**
fix nutanix_image version, set the image version when create the image resource

### CODE REVIEW

**Comment by Haroon-Dweikat-Ntx** [comment]
/ok-to-test TestAccNutanixImage_
> Acceptance test run status: success
> **📌 [View GitHub Actions Run](https://github.com/nutanix/terraform-provider-nutanix/actions/runs/15277411453)**
> Current line coverage (1.8) is below threshold (50). Kindly add more acceptance tests.

**Comment by Haroon-Dweikat-Ntx** [comment]
test log : 
 
 Failed test cases with error Failed state verification, resource with ID terraform-2***25***525***8484***79***1***b not found  duo to terraform version



 ```
 ==================================================🧪 TEST SUMMARY 🧪=================================================================================
Total Test Cases Run 🐹🚀: 9
Total Test Cases Passed 🐹✅: 8 (88 %)
***: syntax error in expression (error token is "***")
Total Test Cases Failed 🐹❌: 1 (11 %)
Total Test Cases Skipped 🐹⚠️: ***
*** ( %)
==================================================================================================================================================
================================================== TESTS SUCCEEDED ✅ =============================================================================
✅ TestAccNutanixImage_basic
✅ TestAccNutanixImage_Update
✅ TestAccNutanixImage_WithLargeImageURL
✅ TestAccNutanixImage_uploadLocal
✅ TestAccNutanixImage_Version
✅ TestAccNutanixImage_WithInvalidConfig
✅ TestAccNutanixImage_WithDataSourceRefInvalidUUID
✅ TestAccNutanixImage_WithDataSourceRef
===================================================================================================================================================
================================================== TESTS FAILED ❌ ================================================================================
/home/ubuntu/actions-runner/_work/_temp/a1281f54-a1af-4d8d-af***5-c5a5ef***187fa.sh: line 611: [: ***
***: integer expression expected
❌ TestAccNutanixImage_WithCategoriesAndCluster
===================================================================================================================================================
================================================== TESTS SKIPPED ⚠️ ==============================================================================
===================================================================================================================================================
================== FAILURE DETAILS OF TESTCASES EXECUTED ===============================================================================================
TESTCASE: TestAccNutanixImage_WithCategoriesAndCluster
========================================🔥🔥🔥🔥📝 TRACEBACK 📝🔥🔥🔥🔥 =======================================================================================
    === RUN   TestAccNutanixImage_WithCategoriesAndCluster
        resource_nutanix_image_test.go:82: Failed state verification, resource with ID terraform-2***25***5271427585486***b not found
    2***25/***5/27 14:28:*** [Debug*** Destroying the category with the ID os_current
    2***25/***5/27 14:28:12 [Debug*** Destroying the category with the ID ubuntu
    2***25/***5/27 14:28:12 [Debug*** Destroying the category with the ID 18.***8
    2***25/***5/27 14:28:13 [Debug*** Destroying the category with the ID os_version
    2***25/***5/27 14:28:13 [Debug*** Destroying the category with the ID os_type
    --- FAIL: TestAccNutanixImage_WithCategoriesAndCluster (69.***8s)
===========================================================================================================================================================

 ```

File: nutanix/services/vmm/resource_nutanix_image.go [hunk 1]
```diff
@@ -627,6 +629,25 @@ func getImageResource(d *schema.ResourceData, image *v3.ImageResources) error {
 		image.Checksum = checks
 	}
 
+	if versionOk {
```
Comment (GullapalliAkhil) [inline nutanix/services/vmm/resource_nutanix_image.go:654]: We allow the user to update version during image update? If yes, just check we have the capability?

Comment (Haroon-Dweikat-Ntx) [reply nutanix/services/vmm/resource_nutanix_image.go:654]: yes we can update image version also, image update version added to test case

**Comment by Haroon-Dweikat-Ntx** [comment]
/ok-to-test TestAccNutanixImage_Version
> Acceptance test run status: failure
> **📌 [View GitHub Actions Run](https://github.com/nutanix/terraform-provider-nutanix/actions/runs/15379492991)**
>

File: nutanix/services/vmm/resource_nutanix_image.go (hunk 1 above)
Comment (GullapalliAkhil) [reply nutanix/services/vmm/resource_nutanix_image.go:654]: Thanks!

**Review by GullapalliAkhil — APPROVED** [review]
LGTM!
