### PR TITLE
Fix cluster import and show errors instead of warning during update and destroy of cluster if not registered with PC.

### LINKED ISSUE #978: Test Import feature for "nutanix_clusters_v2" resource and document the prerequisites.
Test Import feature for "nutanix_clusters_v2" resource and document the prerequisites.

**Script:**
terraform import nutanix_cluster_v2.managed_cluster < managed_cluster_ext_id >

### PR DESCRIPTION
**Pull request by GullapalliAkhil**
Manually Tested:
1. Cluster Create without PC registration.
2. Do update and Destroy, both the events should show a errors.
3. Import of Cluster should show an error "Register cluster with PC"
4. Register PC, should be successful.
5. Update should be successful after registration.
6. Import of cluster should be successful after PC registration.
7. Update of cluster after import should be successful.
8. Destroy of cluster should be successful after PC registration.

* Fix import of cluster
* Doc: Add recommendations for managing cluster.
* Doc: Fix import documentation.

### CODE REVIEW

File: nutanix/services/clustersv2/resource_nutanix_cluster_entity_v2.go [hunk 1]
```diff
@@ -1033,20 +963,8 @@ func ResourceNutanixClusterV2Delete(ctx context.Context, d *schema.ResourceData,
...
-						Severity: diag.Warning,
-						Summary:  "Cluster not found. Please register the cluster to Prism Central if not. If deleted, then reset the state.",
-						Detail:   fmt.Sprintf("Cluster %s not found: %v", d.Get("name").(string), err),
-					},
-				}
-				return diags
-			}
 			log.Printf("[DEBUG] ResourceNutanixClusterV2Delete : error while fetching cluster : %v", err)
-			return diag.Errorf("error while fetching cluster : %v", err)
+			return diag.Errorf("error while fetching cluster : %v: Please register the cluster to Prism Central if not.", err)
```
Comment (Haroon-Dweikat-Ntx) [inline nutanix/services/clustersv2/resource_nutanix_cluster_entity_v2.go:967]: let's do the same thing for delete

**Review by Haroon-Dweikat-Ntx — CHANGES_REQUESTED** [review]

File: nutanix/services/clustersv2/resource_nutanix_cluster_entity_v2.go (hunk 1 above)
Comment (GullapalliAkhil) [reply nutanix/services/clustersv2/resource_nutanix_cluster_entity_v2.go:967]: :-), Didn't get you. This is part of delete. Both update and Delete are handled. Please cross check

**Review by Haroon-Dweikat-Ntx — APPROVED** [review]
LGTM
