### PR TITLE
In Subnets V2, IsNatEnabled should be set to false in api payload if set to false in Tf script

### LINKED ISSUE #820: Error Creating NoNat Overlay External Network
### Nutanix Cluster Information
<!-- 
Please provide the version of:
 - 7.0.1
--2024.3.1

### Terraform Version
Terraform is v1.11.2 running on linux_amd64

### Terraform Configuration Files
```
https://www.dropbox.com/scl/fi/hi736m7331l2xbq3tpthh/terraform_debug.txt?rlkey=y39dpxqok7lorvq22sdvcncrh&dl=0


Issue

When trying to create a NoNat Overlay External Subnet, the operation fails with an error that NAT subnets can't be created of updated.

The code has this value set

  is_nat_enabled = false
  is_external = true

From looking at the request.arg.embedded output, the is_nat_enabled=false value is not passed through

 is_external: true
enable_snat: true

Our engineering team deduced that is_nat_enabled is not sent in api call if its false. 

Screenshot here - https://www.dropbox.com/scl/fi/4c60rhv88s5oa8he88cfd/CB.zip?rlkey=f69pbpeo1mexi63qrvlwlrls9&dl=0

### LINKED ISSUE #980: nutanix_subnet_v2 "is_nat_enabled" not honoring false
### Nutanix Cluster Information
 - Nutanix Cluster (Prism Element / AOS): 7.3.0.7
 - Nutanix Prism Central: pc.7.3.0.6

### Terraform Version
OpenTofu v1.10.6
on darwin_arm64
+ provider registry.opentofu.org/nutanix/nutanix v2.0.0

### Affected Resource(s)
nutanix_subnet_v2

### Terraform Configuration Files
```hcl
resource "nutanix_subnet_v2" "AZ01EXTNONAT" {
  provider               = nutanix.az01
  name                   = "AZ01EXTNONAT"
  description            = "NVD External no-NAT Subnet"
  cluster_reference      = data.nutanix_clusters_v2.az01_app_cluster.cluster_entities[0].ext_id
  subnet_type            = "VLAN"
  network_id             = var.az01_external_network_nonat_vlan_id
  is_advanced_networking = true
  is_external            = true
  is_nat_enabled         = false
  ip_config {
    ipv4 {
      ip_subnet {
        ip {
          value = var.az01_external_network_nonat_network_ip
        }
        prefix_length = var.az01_external_network_nonat_network_prefix
      }
      default_gateway_ip {
        value = var.az01_external_network_nonat_gateway_ip
      }
      pool_list {
        start_ip {
          value = var.az01_external_network_nonat_network_pool_start_ip
        }
        end_ip {
          value = var.az01_external_network_nonat_network_pool_end_ip
        }
      }
    }
  }
}
```
### Debug Output
-

### Panic Output
-

### Expected Behavior
External network created with Nat disabled.

### Actual Behavior
External network created with Nat enabled.

### Steps to Reproduce
1. `terraform apply`

### Important Factors
-
​
### References
-

### PR DESCRIPTION
**Pull request by bhati-pradeep**
Currently, we are not able to create external NoNat overlay subnet. By default is_nat_enabled is true even if its set to false in TF Script.

This is due to bug in TF sdk https://github.com/hashicorp/terraform/issues/4936 where its set `exists` as false when attribute is having zero value. And in API by default NAT is enabled if no value is sent 

Have update code to check the attribute existence and set.

### CODE REVIEW

File: nutanix/services/networkingv2/resource_nutanix_subnets_v2.go [hunk 1]
```diff
@@ -493,7 +493,8 @@ func ResourceNutanixSubnetV2Create(ctx context.Context, d *schema.ResourceData,
 	if vpcRef, ok := d.GetOk("vpc_reference"); ok {
 		inputSpec.VpcReference = utils.StringPtr(vpcRef.(string))
 	}
-	if isNat, ok := d.GetOk("is_nat_enabled"); ok {
+
+	if isNat, ok := d.GetOkExists("is_nat_enabled"); ok {
```
Comment (Haroon-Dweikat-Ntx) [inline nutanix/services/networkingv2/resource_nutanix_subnets_v2.go]: `d.GetOkExists` is deprecated, we should not use it

Comment (bhati-pradeep) [reply nutanix/services/networkingv2/resource_nutanix_subnets_v2.go]: Thanks @Haroon-Dweikat-Ntx. Its deprecated : https://github.com/hashicorp/terraform-plugin-sdk/pull/350

**Comment by bhati-pradeep** [comment]
/ok-to-test TestAccV2NutanixSubnet*

> Acceptance test run status: success
> **📌 [View GitHub Actions Run](https://github.com/nutanix/terraform-provider-nutanix/actions/runs/14341980695)**
> Current line coverage (2.5) is below threshold (50). Kindly add more acceptance tests.

**Comment by bhati-pradeep** [comment]
All subnets v2 tests passed. Test status :
```
==================================================🧪 TEST SUMMARY 🧪=================================================================================
***: syntax error in expression (error token is "***")
Total Test Cases Run 🐹🚀: 7
Total Test Cases Passed 🐹✅: 7 (1*** %)
Total Test Cases Failed 🐹❌: ***
*** ( %)
Total Test Cases Skipped 🐹⚠️: ***
*** ( %)
==================================================================================================================================================
================================================== TESTS SUCCEEDED ✅ =============================================================================
/home/ubuntu/actions-runner/_work/_temp/b66723e1-eb1f-4ecd-966***-1616b***fcf519.sh: line 583: [: ***
***: integer expression expected
/home/ubuntu/actions-runner/_work/_temp/b66723e1-eb1f-4ecd-966***-1616b***fcf519.sh: line 59***: [: ***
***: integer expression expected
/home/ubuntu/actions-runner/_work/_temp/b66723e1-eb1f-4ecd-966***-1616b***fcf519.sh: line 598: [: ***
***: integer expression expected
✅ TestAccV2NutanixSubnetDataSource_Basic
✅ TestAccV2NutanixSubnetsDataSource_Basic
✅ TestAccV2NutanixSubnetsDataSource_WithFilter
✅ TestAccV2NutanixSubnetResource_Basic
✅ TestAccV2NutanixSubnetResource_WithIPPool
✅ TestAccV2NutanixSubnetResource_WithExternalSubnet
✅ TestAccV2NutanixSubnetResource_isNatEnableFalse
===================================================================================================================================================
================================================== TESTS FAILED ❌ ================================================================================
===================================================================================================================================================
================================================== TESTS SKIPPED ⚠️ ==============================================================================
===================================================================================================================================================
Tests Execution is done, please debug if any failures
```

**Review by abhinavbansal29 — APPROVED** [review]
