### PR TITLE
fix VMs with UEFI boot bug

### LINKED ISSUE #725: Version 2.0.0 failed to create a VM with UEFI
trying to create a VM 

    boot_config {
      uefi_boot {
      }
    }

terraform returns an error:

│ Error: Invalid address to set: []string{"boot_config", "0", "uefi_boot", "0", "nvram_device", "0", "backing_storage_info", "0", "disk_ext_id"}

May be I'm wrong but I cant find doc to create uefi vms in version 2.0.0

### PR DESCRIPTION
**Pull request by Haroon-Dweikat-Ntx**
fix VMs with UEFI boot bug, add test case to handle UEFI boot,  and check the schema of the vm module

### CODE REVIEW

File: nutanix/services/vmmv2/resource_nutanix_virtual_machine_v2.go [hunk 1]
```diff
@@ -496,12 +500,77 @@ func ResourceNutanixVirtualMachineV2() *schema.Resource {
 																	},
 																},
 															},
+															"is_migration_in_progress": {
```
Comment (bhati-pradeep) [inline nutanix/services/vmmv2/resource_nutanix_virtual_machine_v2.go:503]: why do we need this ? Whats this used for ?

File: nutanix/services/vmmv2/resource_nutanix_vms_clone_v2.go [hunk 2]
```diff
@@ -326,6 +326,10 @@ func ResourceNutanixVMCloneV2() *schema.Resource {
 													Computed: true,
 													Elem: &schema.Resource{
 														Schema: map[string]*schema.Schema{
+															"disk_ext_id": {
```
Comment (bhati-pradeep) [inline nutanix/services/vmmv2/resource_nutanix_vms_clone_v2.go:329]: whats the usecase for this ?

File: nutanix/services/vmmv2/resource_nutanix_vms_clone_v2_test.go [hunk 3]
```diff
@@ -58,6 +58,29 @@ func TestAccV2NutanixVmsCloneResource_WithGuestCustomization(t *testing.T) {
 	})
 }
 
+func TestAccV2NutanixVmsCloneResource_WithUefiBootConfig(t *testing.T) {
```
Comment (bhati-pradeep) [inline nutanix/services/vmmv2/resource_nutanix_vms_clone_v2_test.go:61]: Can we check if UEFI boot is set correctly after clone ?

**Review by bhati-pradeep — CHANGES_REQUESTED** [review]

File: nutanix/services/vmmv2/resource_nutanix_virtual_machine_v2.go (hunk 1 above)
Comment (Haroon-Dweikat-Ntx) [reply nutanix/services/vmmv2/resource_nutanix_virtual_machine_v2.go:503]: I reviewed the API documentation and found that it was missing from the resource schema

File: nutanix/services/vmmv2/resource_nutanix_vms_clone_v2.go (hunk 2 above)
Comment (Haroon-Dweikat-Ntx) [reply nutanix/services/vmmv2/resource_nutanix_vms_clone_v2.go:329]: I reviewed the API documentation and discovered that it was missing from the resource schema, which was causing the bug that this fix addresses.

**Review by bhati-pradeep — APPROVED** [review]
