### PR TITLE
Fix issue 172: power_state this field cannot be set

### LINKED ISSUE #172: power_state: this field cannot be set
### Nutanix Cluster Information
 - Nutanix Cluster (Prism Element / AOS): 5.10.10.1 LTS
 - Nutanix Prism Central: 5.16.1.3

### Terraform Version

```shell
$ terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/-/nutanix v1.1.0
+ provider registry.terraform.io/terraform-providers/nutanix v1.1.0
```

### Affected Resource(s)
* nutanix_virtual_machine

### Terraform Configuration Files
```hcl
resource "nutanix_virtual_machine" "tf-69373009-9823-8102-24d5-983ee575ec85" {
  name = "server01.example.com"
  cluster_uuid = "00056dce***"
  memory_size_mib = "2048"
  num_sockets = "1"
  power_state = "OFF"
  use_hot_add = false
  guest_customization_cloud_init_user_data = "[snip]"
  nic_list {
    subnet_uuid = "246285c9-d1e3-4050-ba0d-5b2be8713681"
  }
  disk_list {
    data_source_reference = {
      kind = "image"
      uuid = "79e63e65-cf7d-4b4e-96a2-68378df369ee"
    }
  }
  lifecycle {
    prevent_destroy = true
    ignore_changes = [
      nic_list,
      disk_list,
      guest_customization_cloud_init_user_data,
    ]
  }
}
```
### Debug Output
https://gist.github.com/mritzmann/be89f883bd71d3a06877e55c821b51a0

### Panic Output
There is no panic output.

### Expected Behavior
The running VM should be shut down.

### Actual Behavior
```shell
$ terraform plan -lock=false -target nutanix_virtual_machine.tf-69373009-9823-8102-24d5-983ee575ec85

Error: "power_state": this field cannot be set

  on QS7yQkgYpJKtLeERd-server01.example.com.tf line 1, in resource "nutanix_virtual_machine" "tf-69373009-9823-8102-24d5-983ee575ec85":
   1: resource "nutanix_virtual_machine" "tf-69373009-9823-8102-24d5-983ee575ec85" {
```

### Steps to Reproduce
1. Create a new Server that match my provided template (but without `power_state`)
2. Add `power_state` and run `terraform plan -target nutanix_virtual_machine.tf-69373009-9823-8102-24d5-983ee575ec85`

### Important Factors
We mange several hundreds vms with terraform, so i redacted some information in the debug output.
​
### References
Similar Issues, but closed:
* https://github.com/nutanix/terraform-provider-nutanix/issues/98
* https://github.com/nutanix/terraform-provider-nutanix/issues/94

### PR DESCRIPTION
**Pull request by Haroon-Dweikat-Ntx**
fix power_state: this field cannot be set issue, change the attribute from computed to computed and optional and handle it in create and update

### CODE REVIEW

**Comment by Haroon-Dweikat-Ntx** [comment]
/ok-to-test TestAccNutanixVirtualMachine_PowerStateTest
> Acceptance test run status: success
> **📌 [View GitHub Actions Run](https://github.com/nutanix/terraform-provider-nutanix/actions/runs/15192385121)**
> Current line coverage (2.5) is below threshold (50). Kindly add more acceptance tests.

**Comment by Haroon-Dweikat-Ntx** [comment]
✅ TestAccNutanixVirtualMachine_PowerStateTest

**Comment by Haroon-Dweikat-Ntx** [comment]
/ok-to-test TestAccNutanixVirtualMachine_

> Acceptance test run status: success
> **📌 [View GitHub Actions Run](https://github.com/nutanix/terraform-provider-nutanix/actions/runs/15236113610)**
> Current line coverage (3.8) is below threshold (50). Kindly add more acceptance tests.

**Comment by Haroon-Dweikat-Ntx** [comment]
Test Report : 
Failed test cases with error `Failed state verification, resource with ID terraform-2***25***525***8484***79***1***b not found
` duo to terraform version 

```
==================================================================================================================================================
================================================== TESTS SUCCEEDED ✅ =============================================================================

✅ TestAccNutanixVirtualMachine_WithSubnet
✅ TestAccNutanixVirtualMachine_cloningVM
✅ TestAccNutanixVirtualMachine_withDiskContainer
✅ TestAccNutanixVirtualMachine_resizeDiskClone
✅ TestAccNutanixVirtualMachine_SecureBootWithNoMachineType
✅ TestAccNutanixVirtualMachine_PowerStateTest
===================================================================================================================================================
================================================== TESTS FAILED ❌ ================================================================================

❌ TestAccNutanixVirtualMachine_basic
❌ TestAccNutanixVirtualMachine_WithDisk
❌ TestAccNutanixVirtualMachine_hotadd
❌ TestAccNutanixVirtualMachine_updateFields
❌ TestAccNutanixVirtualMachine_WithSerialPortList
❌ TestAccNutanixVirtualMachine_PowerStateMechanism
❌ TestAccNutanixVirtualMachine_CdromGuestCustomisationReboot
❌ TestAccNutanixVirtualMachine_CdromGuestCustomisationRebootWithManualCDROM
❌ TestAccNutanixVirtualMachine_CloudInitCustomKeyValues
❌ TestAccNutanixVirtualMachine_DeviceProperties
❌ TestAccNutanixVirtualMachine_CloudInitUserData
❌ TestAccNutanixVirtualMachine_Ngt
❌ TestAccNutanixVirtualMachine_SysprepCustomKeyValues
❌ TestAccNutanixVirtualMachine_SecureBoot
===================================================================================================================================================
================================================== TESTS SKIPPED ⚠️ ==============================================================================
===================================================================================================================================================

================== FAILURE DETAILS OF TESTCASES EXECUTED ===============================================================================================
TESTCASE: TestAccNutanixVirtualMachine_basic
========================================🔥🔥🔥🔥📝 TRACEBACK 📝🔥🔥🔥🔥 =======================================================================================
    === RUN   TestAccNutanixVirtualMachine_basic
    2***25/***5/25 ***8:48:17 [Debug*** Updating VM values cd43***2***c-9262-4f69-b3***2-8717c2917689
        resource_nutanix_virtual_machine_test.go:22: Failed state verification, resource with ID terraform-2***25***525***8484***79***1***b not found
    --- FAIL: TestAccNutanixVirtualMachine_basic (112.54s)
===========================================================================================================================================================
TESTCASE: TestAccNutanixVirtualMachine_WithDisk
========================================🔥🔥🔥🔥📝 TRACEBACK 📝🔥🔥🔥🔥 =======================================================================================
    === RUN   TestAccNutanixVirtualMachine_WithDisk
    2***25/***5/25 ***8:5***:33 [Debug*** Updating VM values 9da1f9ec-1***f***-48***5-8698-c6a378f7bf69
        resource_nutanix_virtual_machine_test.go:65: Failed state verification, resource with ID terraform-2***25***525***85***566877***16 not found
    --- FAIL: TestAccNutanixVirtualMachine_WithDisk (15***.***7s)
===========================================================================================================================================================
TESTCASE: TestAccNutanixVirtualMachine_hotadd
========================================🔥🔥🔥🔥📝 TRACEBACK 📝🔥🔥🔥🔥 =======================================================================================
    === RUN   TestAccNutanixVirtualMachine_hotadd
    2***25/***5/25 ***8:51:32 m.PowerStateMechanism was nil, setting correct value!
    2***25/***5/25 ***8:53:***3 [Debug*** Updating VM values 26f8cf13-a1bb-4ec***-94ac-4796ee67239a
        resource_nutanix_virtual_machine_test.go:1***8: Failed state verification, resource with ID terraform-2***25***525***853359462***21 not found
    --- FAIL: TestAccNutanixVirtualMachine_hotadd (156.17s)
===========================================================================================================================================================
TESTCASE: TestAccNutanixVirtualMachine_updateFields
========================================🔥🔥🔥🔥📝 TRACEBACK 📝🔥🔥🔥🔥 =======================================================================================
    === RUN   TestAccNutanixVirtualMachine_updateFields
    2***25/***5/25 ***8:55:15 [Debug*** Updating VM values 1c55b7b9-72a4-4a1d-b987-a3dcd6796d14
        resource_nutanix_virtual_machine_test.go:148: Failed state verification, resource with ID terraform-2***25***525***8555***289***2c not found
    --- FAIL: TestAccNutanixVirtualMachine_updateFields (122.82s)
===========================================================================================================================================================
TESTCASE: TestAccNutanixVirtualMachine_WithSerialPortList
========================================🔥🔥🔥🔥📝 TRACEBACK 📝🔥🔥🔥🔥 =======================================================================================
    === RUN   TestAccNutanixVirtualMachine_WithSerialPortList
        resource_nutanix_virtual_machine_test.go:226: Step 1/2 error: Check failed: Check 8/9 error: nutanix_virtual_machine.vm5: Attribute 'serial_port_list.***.index' not found
    --- FAIL: TestAccNutanixVirtualMachine_WithSerialPortList (8***.86s)
===========================================================================================================================================================
TESTCASE: TestAccNutanixVirtualMachine_PowerStateMechanism
========================================🔥🔥🔥🔥📝 TRACEBACK 📝🔥🔥🔥🔥 =======================================================================================
    === RUN   TestAccNutanixVirtualMachine_PowerStateMechanism
    2***25/***5/25 ***8:59:*** m.PowerStateMechanism was nil, setting correct value!
        resource_nutanix_virtual_machine_test.go:258: Failed state verification, resource with ID terraform-2***25***525***9***161394***3e not found
    --- FAIL: TestAccNutanixVirtualMachine_PowerStateMechanism (85.34s)
===========================================================================================================================================================
TESTCASE: TestAccNutanixVirtualMachine_CdromGuestCustomisationReboot
========================================🔥🔥🔥🔥📝 TRACEBACK 📝🔥🔥🔥🔥 =======================================================================================
    === RUN   TestAccNutanixVirtualMachine_CdromGuestCustomisationReboot
        resource_nutanix_virtual_machine_test.go:283: Failed state verification, resource with ID terraform-2***25***525***9***14***919***44 not found
    --- FAIL: TestAccNutanixVirtualMachine_CdromGuestCustomisationReboot (84.77s)
    === RUN   TestAccNutanixVirtualMachine_CdromGuestCustomisationRebootWithManualCDROM
        resource_nutanix_virtual_machine_test.go:3***7: Failed state verification, resource with ID terraform-2***25***525***9***3***5931***4a not found
    --- FAIL: TestAccNutanixVirtualMachine_CdromGuestCustomisationRebootWithManualCDROM (85.41s)
===========================================================================================================================================================
TESTCASE: TestAccNutanixVirtualMachine_CdromGuestCustomisationRebootWithManualCDROM
========================================🔥🔥🔥🔥📝 TRACEBACK 📝🔥🔥🔥🔥 =======================================================================================
    === RUN   TestAccNutanixVirtualMachine_CdromGuestCustomisationRebootWithManualCDROM
        resource_nutanix_virtual_machine_test.go:3***7: Failed state verification, resource with ID terraform-2***25***525***9***3***5931***4a not found
    --- FAIL: TestAccNutanixVirtualMachine_CdromGuestCustomisationRebootWithManualCDROM (85.41s)
===========================================================================================================================================================
TESTCASE: TestAccNutanixVirtualMachine_CloudInitCustomKeyValues
========================================🔥🔥🔥🔥📝 TRACEBACK 📝🔥🔥🔥🔥 =======================================================================================
    === RUN   TestAccNutanixVirtualMachine_CloudInitCustomKeyValues
        resource_nutanix_virtual_machine_test.go:331: Failed state verification, resource with ID terraform-2***25***525***9***43134***3***5*** not found
    --- FAIL: TestAccNutanixVirtualMachine_CloudInitCustomKeyValues (88.67s)
===========================================================================================================================================================
TESTCASE: TestAccNutanixVirtualMachine_DeviceProperties
========================================🔥🔥🔥🔥📝 TRACEBACK 📝🔥🔥🔥🔥 =======================================================================================
    === RUN   TestAccNutanixVirtualMachine_DeviceProperties
        resource_nutanix_virtual_machine_test.go:361: Failed state verification, resource with ID terraform-2***25***525***9***6123427***56 not found
    --- FAIL: TestAccNutanixVirtualMachine_DeviceProperties (1***8.38s)
===========================================================================================================================================================
TESTCASE: TestAccNutanixVirtualMachine_CloudInitUserData
========================================🔥🔥🔥🔥📝 TRACEBACK 📝🔥🔥🔥🔥 =======================================================================================
    === RUN   TestAccNutanixVirtualMachine_CloudInitUserData
        resource_nutanix_virtual_machine_test.go:475: Failed state verification, resource with ID terraform-2***25***525***[914](https://github.com/nutanix/terraform-provider-nutanix/actions/runs/15236113610/job/42850176467#step:16:914)572***6***75 not found
    --- FAIL: TestAccNutanixVirtualMachine_CloudInitUserData (88.58s)
===========================================================================================================================================================
TESTCASE: TestAccNutanixVirtualMachine_Ngt
========================================🔥🔥🔥🔥📝 TRACEBACK 📝🔥🔥🔥🔥 =======================================================================================
    === RUN   TestAccNutanixVirtualMachine_Ngt
    2***25/***5/25 ***9:16:4*** [Debug*** Updating VM values b1c***f141-***5a9-4fc7-9ed9-75de***1b26c37
        resource_nutanix_virtual_machine_test.go:5***4: Failed state verification, resource with ID terraform-2***25***525***[917](https://github.com/nutanix/terraform-provider-nutanix/actions/runs/15236113610/job/42850176467#step:16:917)1598***1***8*** not found
    --- FAIL: TestAccNutanixVirtualMachine_Ngt (149.39s)
===========================================================================================================================================================
TESTCASE: TestAccNutanixVirtualMachine_SysprepCustomKeyValues
========================================🔥🔥🔥🔥📝 TRACEBACK 📝🔥🔥🔥🔥 =======================================================================================
    === RUN   TestAccNutanixVirtualMachine_SysprepCustomKeyValues
        resource_nutanix_virtual_machine_test.go:546: Failed state verification, resource with ID terraform-2***25***525***[918](https://github.com/nutanix/terraform-provider-nutanix/actions/runs/15236113610/job/42850176467#step:16:918)55485***86 not found
    --- FAIL: TestAccNutanixVirtualMachine_SysprepCustomKeyValues (85.31s)
===========================================================================================================================================================
TESTCASE: TestAccNutanixVirtualMachine_SecureBoot
========================================🔥🔥🔥🔥📝 TRACEBACK 📝🔥🔥🔥🔥 =======================================================================================
    === RUN   TestAccNutanixVirtualMachine_SecureBoot
    2***25/***5/25 ***9:2***:24 [Debug*** Updating VM values ***5511fa1-7122-429d-abd***-75a4358ccc21
        resource_nutanix_virtual_machine_test.go:581: Failed state verification, resource with ID terraform-2***25***525***92***467986***91 not found
    --- FAIL: TestAccNutanixVirtualMachine_SecureBoot (111.27s)
```

File: nutanix/services/vmm/resource_nutanix_virtual_machine_test.go [hunk 1]
```diff
@@ -641,6 +641,34 @@ func TestAccNutanixVirtualMachine_SecureBootWithNoMachineType(t *testing.T) {
...
+				Config: testAccNutanixVMConfigPowerState(r, "ON"),
+				Check: resource.ComposeTestCheckFunc(
+					testAccCheckNutanixVirtualMachineExists(resourceName),
+					resource.TestCheckResourceAttr(resourceName, "power_state", "ON"),
+				),
+			},
+		},
+	})
+}
+
```
Comment (GullapalliAkhil) [inline nutanix/services/vmm/resource_nutanix_virtual_machine_test.go:687]: Can we add a testcase where VM will be created in ON state by default but during update will add power_state is OFF

Comment (Haroon-Dweikat-Ntx) [reply nutanix/services/vmm/resource_nutanix_virtual_machine_test.go:687]: test case added

**Comment by Haroon-Dweikat-Ntx** [comment]
/ok-to-test TestAccNutanixVirtualMachine_
> Acceptance test run status: success
> **📌 [View GitHub Actions Run](https://github.com/nutanix/terraform-provider-nutanix/actions/runs/15386472118)**
> Current line coverage (3.8) is below threshold (50). Kindly add more acceptance tests.

**Review by GullapalliAkhil — APPROVED** [review]
