### PR TITLE
Fix issue 835: provider plugin panic when trying to add multiple security policies

### LINKED ISSUE #835: provider plugin panic when trying to add multiple security policies
###Nutanix Cluster Information
Nutanix Cluster (Prism Element / AOS): 7.0.1
Nutanix Prism Central: pc.2024.3.1

###Terraform Version
Terraform v1.11.4
on darwin_arm64
provider registry.terraform.io/nutanix/nutanix v2.2.0

### Affected Resource(s)
* nutanix_network_security_policy_v2

### Terraform Configuration Files
variables.tf
```hcl
#define the type of variables to be used in terraform file
variable "nutanix_username" {
  type = string
}
variable "nutanix_password" {
  type = string
}
variable "nutanix_endpoint" {
  type = string
}
variable "vpc_name" {
  type = string
}
```
vpcs.tf:
```hcl
data "nutanix_vpcs_v2" "vpcs"{
  limit = 1
  filter = "name eq '${var.vpc_name}'"
}
````
main.tf:
```hcl
terraform {
  required_providers {
    nutanix = {
      source  = "nutanix/nutanix"
      version = ">= 2.0.0"
    }
  }
}

#defining nutanix configuration
provider "nutanix" {
  username = var.nutanix_username
  password = var.nutanix_password
  endpoint = var.nutanix_endpoint
  port     = 9440
  insecure = true
}
````
categories.tf:
```hcl
locals {
  app_count = 1
}


data "nutanix_categories_v2" "app_type" {
  count  = local.app_count
  limit  = 1
  filter = "key eq 'AppType' and value eq 'NVDMultiVmApp${format("%02d", count.index + 1)}'"
}

data "nutanix_categories_v2" "app_tier_app" {
  limit  = 1
  filter = "key eq 'AppTier' and value eq 'App'"
}

data "nutanix_categories_v2" "app_tier_db" {
  limit  = 1
  filter = "key eq 'AppTier' and value eq 'DB'"
}

data "nutanix_categories_v2" "app_tier_web" {
  limit  = 1
  filter = "key eq 'AppTier' and value eq 'Web'"
}
````
security_policies.tf:
```hcl
locals {
  isolation_policy_count = 1
  vlan_policies = 0
  vpc_policies = 2
}

resource "nutanix_network_security_policy_v2" "vlan_app" {
  count       = local.vlan_policies
  name        = "NVDMultiVmApp${format("%02d", count.index + 1)}"
  description = "Application policy for NVDMultiVmApp${format("%02d", count.index + 1)}"
  type        = "APPLICATION"
  state       = "ENFORCE"

  lifecycle {
    create_before_destroy = true
    ignore_changes = [name, description]
  }

#* outbound rules
  rules {
    description = "outbound for app tier"
    type        = "APPLICATION"
    spec {
      application_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_app.categories[0].ext_id,
        ]
        src_category_references = []
        is_all_protocol_allowed = true
        src_allow_spec = "NONE"
      }
    }
  }

  rules {
    description = "outbound for db tier"
    type        = "APPLICATION"
    spec {
      application_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_db.categories[0].ext_id,
        ]
        src_category_references = []
        is_all_protocol_allowed = true
        src_allow_spec = "NONE"
      }
    }
  }

  rules {
    description = "outbound for web tier"
    type        = "APPLICATION"
    spec {
      application_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_web.categories[0].ext_id,
        ]
        src_category_references = []
        is_all_protocol_allowed = true
        src_allow_spec = "NONE"
      }
    }
  }

#* preventing vms with same tier from talking with each other
  rules {
    description = "deny amongst app tier"
    type        = "INTRA_GROUP"
    spec {
      intra_entity_group_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_app.categories[0].ext_id,
        ]
        secured_group_action = "DENY"
      }
    }
  }
  
  rules {
    description = "deny amongst db tier"
    type        = "INTRA_GROUP"
    spec {
      intra_entity_group_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_db.categories[0].ext_id,
        ]
        secured_group_action = "DENY"
      }
    }
  }

  rules {
    description = "deny amongst web tier"
    type        = "INTRA_GROUP"
    spec {
      intra_entity_group_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_web.categories[0].ext_id,
        ]
        secured_group_action = "DENY"
      }
    }
  }

#* ALL inbound rules
  rules {
    description = "ALL inbound for app tier"
    type        = "APPLICATION"
    spec {
      application_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_app.categories[0].ext_id,
        ]
        src_category_references = []
        is_all_protocol_allowed = false
        src_allow_spec = "ALL"
        tcp_services {
          start_port = 22
          end_port = 22
        }
        tcp_services {
          start_port = 443
          end_port = 443
        }
        tcp_services {
          start_port = 2074
          end_port   = 2074
        }
        tcp_services {
          start_port = 3389
          end_port = 3389
        }
        tcp_services {
          start_port = 5985
          end_port   = 5985
        }
        icmp_services {
          type = 8
          code = 0
        }
      }
    }
  }

  rules {
    description = "ALL inbound for db tier"
    type        = "APPLICATION"
    spec {
      application_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_db.categories[0].ext_id,
        ]
        src_category_references = []
        is_all_protocol_allowed = false
        src_allow_spec = "ALL"
        tcp_services {
          start_port = 22
          end_port = 22
        }
        tcp_services {
          start_port = 2074
          end_port   = 2074
        }
        tcp_services {
          start_port = 3389
          end_port = 3389
        }
        tcp_services {
          start_port = 5985
          end_port   = 5985
        }
        icmp_services {
          type = 8
          code = 0
        }
      }
    }
  }

  rules {
    description = "ALL inbound for web tier"
    type        = "APPLICATION"
    spec {
      application_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_web.categories[0].ext_id,
        ]
        src_category_references = []
        is_all_protocol_allowed = false
        src_allow_spec = "ALL"
        tcp_services {
          start_port = 22
          end_port = 22
        }
        tcp_services {
          start_port = 443
          end_port = 443
        }
        tcp_services {
          start_port = 2074
          end_port   = 2074
        }
        tcp_services {
          start_port = 3389
          end_port = 3389
        }
        tcp_services {
          start_port = 5985
          end_port   = 5985
        }
        icmp_services {
          type = 8
          code = 0
        }
      }
    }
  }

#* inbound between tiers
  rules {
    description = "web inbound to app tier"
    type        = "APPLICATION"
    spec {
      application_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_app.categories[0].ext_id,
        ]
        src_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_web.categories[0].ext_id,
        ]
        is_all_protocol_allowed = false
        tcp_services {
          start_port = 2066
          end_port = 2066
        }
      }
    }
  }

  rules {
    description = "app inbound to db tier"
    type        = "APPLICATION"
    spec {
      application_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_db.categories[0].ext_id,
        ]
        src_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_app.categories[0].ext_id,
        ]
        is_all_protocol_allowed = false
        tcp_services {
          start_port = 3336
          end_port = 3336
        }
      }
    }
  }


  is_hitlog_enabled = true
}

resource "nutanix_network_security_policy_v2" "vpc_app" {
  count       = local.vpc_policies
  name        = "NVDMultiVmApp${format("%02d", count.index + 1)}"
  description = "Application policy for NVDMultiVmApp${format("%02d", count.index + 1)}"
  type        = "APPLICATION"
  state       = "ENFORCE"
  scope       = "VPC_LIST"
  
  vpc_reference = [
    data.nutanix_vpcs_v2.vpcs.vpcs[0].ext_id,
  ]

  lifecycle {
    create_before_destroy = true
    ignore_changes = [name, description]
  }

#* outbound rules
  rules {
    description = "outbound for app tier"
    type        = "APPLICATION"
    spec {
      application_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_app.categories[0].ext_id,
        ]
        src_category_references = []
        is_all_protocol_allowed = true
        src_allow_spec = "NONE"
      }
    }
  }

  rules {
    description = "outbound for db tier"
    type        = "APPLICATION"
    spec {
      application_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_db.categories[0].ext_id,
        ]
        src_category_references = []
        is_all_protocol_allowed = true
        src_allow_spec = "NONE"
      }
    }
  }

  rules {
    description = "outbound for web tier"
    type        = "APPLICATION"
    spec {
      application_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_web.categories[0].ext_id,
        ]
        src_category_references = []
        is_all_protocol_allowed = true
        src_allow_spec = "NONE"
      }
    }
  }

#* preventing vms with same tier from talking with each other
  rules {
    description = "deny amongst app tier"
    type        = "INTRA_GROUP"
    spec {
      intra_entity_group_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_app.categories[0].ext_id,
        ]
        secured_group_action = "DENY"
      }
    }
  }
  
  rules {
    description = "deny amongst db tier"
    type        = "INTRA_GROUP"
    spec {
      intra_entity_group_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_db.categories[0].ext_id,
        ]
        secured_group_action = "DENY"
      }
    }
  }

  rules {
    description = "deny amongst web tier"
    type        = "INTRA_GROUP"
    spec {
      intra_entity_group_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_web.categories[0].ext_id,
        ]
        secured_group_action = "DENY"
      }
    }
  }

#* ALL inbound rules
  rules {
    description = "ALL inbound for app tier"
    type        = "APPLICATION"
    spec {
      application_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_app.categories[0].ext_id,
        ]
        src_category_references = []
        is_all_protocol_allowed = false
        src_allow_spec = "ALL"
        tcp_services {
          start_port = 22
          end_port = 22
        }
        tcp_services {
          start_port = 443
          end_port = 443
        }
        tcp_services {
          start_port = 2074
          end_port   = 2074
        }
        tcp_services {
          start_port = 3389
          end_port = 3389
        }
        tcp_services {
          start_port = 5985
          end_port   = 5985
        }
        icmp_services {
          type = 8
          code = 0
        }
      }
    }
  }

  rules {
    description = "ALL inbound for db tier"
    type        = "APPLICATION"
    spec {
      application_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_db.categories[0].ext_id,
        ]
        src_category_references = []
        is_all_protocol_allowed = false
        src_allow_spec = "ALL"
        tcp_services {
          start_port = 22
          end_port = 22
        }
        tcp_services {
          start_port = 2074
          end_port   = 2074
        }
        tcp_services {
          start_port = 3389
          end_port = 3389
        }
        tcp_services {
          start_port = 5985
          end_port   = 5985
        }
        icmp_services {
          type = 8
          code = 0
        }
      }
    }
  }

  rules {
    description = "ALL inbound for web tier"
    type        = "APPLICATION"
    spec {
      application_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_web.categories[0].ext_id,
        ]
        src_category_references = []
        is_all_protocol_allowed = false
        src_allow_spec = "ALL"
        tcp_services {
          start_port = 22
          end_port = 22
        }
        tcp_services {
          start_port = 443
          end_port = 443
        }
        tcp_services {
          start_port = 2074
          end_port   = 2074
        }
        tcp_services {
          start_port = 3389
          end_port = 3389
        }
        tcp_services {
          start_port = 5985
          end_port   = 5985
        }
        icmp_services {
          type = 8
          code = 0
        }
      }
    }
  }

#* inbound between tiers
  rules {
    description = "web inbound to app tier"
    type        = "APPLICATION"
    spec {
      application_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_app.categories[0].ext_id,
        ]
        src_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_web.categories[0].ext_id,
        ]
        is_all_protocol_allowed = false
        tcp_services {
          start_port = 2066
          end_port = 2066
        }
      }
    }
  }

  rules {
    description = "app inbound to db tier"
    type        = "APPLICATION"
    spec {
      application_rule_spec {
        secured_group_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_db.categories[0].ext_id,
        ]
        src_category_references = [
          try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
          data.nutanix_categories_v2.app_tier_app.categories[0].ext_id,
        ]
        is_all_protocol_allowed = false
        tcp_services {
          start_port = 3336
          end_port = 3336
        }
      }
    }
  }


  is_hitlog_enabled = true
}

resource "nutanix_network_security_policy_v2" "isolation" {
  count       = local.isolation_policy_count
  name        = "NVDMultiVmApp${format("%02d", count.index + 1)}_isolation"
  description = "Isolation rule for NVDMultiVmApp${format("%02d", count.index + 1)}"
  type        = "ISOLATION"
  state       = "ENFORCE"

  lifecycle {
    create_before_destroy = true
    ignore_changes = [name, description]
  }

  rules {
    description = "Isolation rule for NVDMultiVmApp${format("%02d", count.index + 1)}"
    type        = "MULTI_ENV_ISOLATION"
    spec {
      multi_env_isolation_rule_spec {
        spec {
          all_to_all_isolation_group {
            isolation_group {
              group_category_references = [
                try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
                data.nutanix_categories_v2.app_tier_app.categories[0].ext_id
              ]
            }
            isolation_group {
              group_category_references = [
                try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
                data.nutanix_categories_v2.app_tier_db.categories[0].ext_id
              ]
            }
            isolation_group {
              group_category_references = [
                try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, ""),
                data.nutanix_categories_v2.app_tier_web.categories[0].ext_id
              ]
            }
          }
        }
      }
    }
  }

  is_hitlog_enabled = true
}
```

### Panic Output
```sh
Error: Plugin did not respond
│ 
│   with nutanix_network_security_policy_v2.vpc_app[1],
│   on security_policies.tf line 277, in resource "nutanix_network_security_policy_v2" "vpc_app":
│  277: resource "nutanix_network_security_policy_v2" "vpc_app" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-nutanix_v2.2.0 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 47 [running]:
github.com/terraform-providers/terraform-provider-nutanix/nutanix/services/networkingv2.expandStringList(...)
        github.com/terraform-providers/terraform-provider-nutanix/nutanix/services/networkingv2/resource_nutanix_subnets_v2.go:1365
github.com/terraform-providers/terraform-provider-nutanix/nutanix/services/networkingv2.expandOneOfNetworkSecurityPolicyRuleSpec({0x10376be80?, 0x14000b8ec48?})
        github.com/terraform-providers/terraform-provider-nutanix/nutanix/services/networkingv2/resource_nutanix_network_security_policies_v2.go:809 +0x1c9c
github.com/terraform-providers/terraform-provider-nutanix/nutanix/services/networkingv2.expandNetworkSecurityPolicyRule({0x1400034d1e0, 0xb, 0x14000e02ca0?})
        github.com/terraform-providers/terraform-provider-nutanix/nutanix/services/networkingv2/resource_nutanix_network_security_policies_v2.go:772 +0x3cc
github.com/terraform-providers/terraform-provider-nutanix/nutanix/services/networkingv2.ResourceNutanixNetworkSecurityPolicyV2Create({0x10399aeb8, 0x140014957a0}, 0x0?, {0x10374bf40?, 0x14000c83440?})
        github.com/terraform-providers/terraform-provider-nutanix/nutanix/services/networkingv2/resource_nutanix_network_security_policies_v2.go:455 +0x568
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x140009a7880, {0x10399ae48, 0x1400028ed20}, 0x2?, {0x10374bf40, 0x14000c83440})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:341 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140009a7880, {0x10399ae48, 0x1400028ed20}, 0x1400116edd0, 0x14000fb7280, {0x10374bf40, 0x14000c83440})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x67c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400024e078, {0x10399ae48, 0x1400028ed20}, 0x1400028ed70)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xabc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14000116400, {0x10399ae10?, 0x14000d981e0?}, 0x14000ed4000)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x20c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x10393e060?, 0x14000116400}, {0x10399ae10, 0x14000d981e0}, 0x14000b905a0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002df500, {0x10399f8d0, 0x140001ee780}, 0x14000f02000, 0x140007d4d20, 0x104136ea0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0xa58
google.golang.org/grpc.(*Server).handleStream(0x140002df500, {0x10399f8d0, 0x140001ee780}, 0x14000f02000, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0x7cc
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.32.0/server.go:859 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 39
        google.golang.org/grpc@v1.32.0/server.go:857 +0x24c

Error: The terraform-provider-nutanix_v2.2.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior
2 application security and 1 isolation policies should be created.

### Actual Behavior
provider plugin crashes and no policies are created.

### Steps to Reproduce
1. `terraform apply`
2. if you change vpc policies to 1, it works.

### PR DESCRIPTION
**Pull request by Haroon-Dweikat-Ntx**
passing an empty string ("") as a UUID reference in your resource configuration, like this:
try(data.nutanix_categories_v2.app_type[count.index].categories[0].ext_id, "")

The empty string is what's causing the issue.

validation added on expand method to ignore empty or nil values

### CODE REVIEW

File: nutanix/common/common.go [hunk 1]
```diff
@@ -33,3 +39,15 @@ func IsExplicitlySet(d *schema.ResourceData, key string) bool {
 	}
 	return false
 }
+
+// ExtIdValidation checks if a given string is a valid UUID.
+// It uses a regular expression to validate the UUID format.
+var uuidRegex = regexp.MustCompile(`^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$`)
+
+func ExtIDValidation(val interface{}, key string) (warns []string, errs []error) {
```
Comment (GullapalliAkhil) [inline nutanix/common/common.go]: What's the use of this function if not consumed?

Comment (Haroon-Dweikat-Ntx) [reply nutanix/common/common.go]: I initially added it for UUID validation, but later decided to remove it since the API already handles this level of validation.
I'll go ahead and remove it.

**Review by GullapalliAkhil — APPROVED** [review]
