### PR TITLE
Fix Issue 897: "" string on update user issue 

### LINKED ISSUE #897: nutanix_users_v2 - Can't change local user password
### Terraform Version

It is a GitLab pipeline, run a gitlab provided official docker image, uses opentofu:
```
registry.gitlab.com/components/opentofu/gitlab-opentofu:2.10.2-opentofu1.9.1-alpine
```

### Affected Resource(s)

* nutanix_users_v2
### Terraform Configuration Files

```hcl
#main.tf

resource "nutanix_users_v2" "user" {
  for_each             = var.nutanix_users
  username             = each.value.username
  user_type            = each.value.user_type
  password             = var.nutanix_user_passwords[each.key]
  email_id             = each.value.email
  display_name         = each.value.display_name
  first_name           = each.value.first_name
  last_name            = each.value.last_name
  force_reset_password = each.value.force_reset_password
  status               = each.value.status
}

#vars.tf
variable "pc" {
  description = "Connection details for Nutanix. This can be Prism Central and Prism element as well." 
  type = object({
    address = string
    username = string
    password = string
  })
}

variable "nutanix_user_passwords" {
  type = map(string)
  sensitive = true
}

variable "nutanix_users" {
  type = map(object({
    username             = string
    email                = string
    user_type            = string
    display_name         = string
    first_name           = string
    last_name            = string
    force_reset_password = bool
    status               = string
  }))
}

#test.tfvars
nutanix_users = {
  "test1" = {
    username             = "test_1"
    email                = "some@email.com"
    user_type            = "LOCAL"
    display_name         = "test_1"
    first_name           = "NetBox"
    last_name            = "Service Account"
    force_reset_password = false
    status               = "ACTIVE"
  },
  "test2" = {
    username             = "test_2"
    email                = "some2@email.com"
    user_type            = "LOCAL"
    display_name         = "test_2"
    first_name           = "NetBox"
    last_name            = "Service Account"
    force_reset_password = false
    status               = "ACTIVE"
  }
}

#provider.tf

terraform {
  required_providers {
    nutanix = {
      source = "nutanix/nutanix"
      version = "2.3.0"
    }
  }
}

provider "nutanix" {
  endpoint     = var.pc.address
  username     = var.pc.username
  password     = var.pc.password
  insecure     = true
  wait_timeout = 30
  session_auth = true
}
```

### Expected Behavior

IaC plan detect the password change, apply the change, and user has the new password associated with it.

### Actual Behavior

The code runs without issue for first try (to create user with original password). But when you change the password of the user, in IaC code, OpenToFu / Terraform should detect, and apply the password changes in the nutanix (prims central, or prism element). Instead of that, plan detects the changes, IaC code runs, and looks like password changed, but not in the the Prism Central. The user has the same, original password.

So tofu / terraform thinks, the password was changed for the user, for next plan(s) it does not detect any drift, but in reality, the user's password was not changed.

### Steps to Reproduce

1. `terraform apply`
### Important Factors

* #0000

### LINKED ISSUE #949: Bug Report: resource "nutanix_users_v2"
## Nutanix Cluster Information
Prism Central Version: pc.7.3.0.5
AOS Version: 7.3.0.5

## Terraform Version
Terraform: v1.13.1
Provider: registry.terraform.io/nutanix/nutanix v2.3.1

## Affected Resources
- resource "nutanix_users_v2"

## Terraform Configuration Files
```terraform
# main.tf

terraform {
  required_providers {
    nutanix = {
      source  = "nutanix/nutanix"
      version = "2.3.1"
    }
    random = {
      source ="hashicorp/random"
      version = "~> 3.0"
    }
  }
}

variable user_resource_password {
    type=string
}

// Generate user suffix
resource "random_string" "user_suffix" {
  length  = 6
  upper   = false
  special = false
}

// Create user with tf
resource "nutanix_users_v2" my_tf_user {
  username = "my_tf_user_${random_string.user_suffix.result}"
  user_type = "LOCAL"
  first_name = "my"
  last_name = "tf user"
  password = var.user_resource_password
  email_id = "something@example.comm"
}

// No schema validation for the user below, will fail on runtime because IdpId is not supplied.
//resource "nutanix_users_v2" my_tf_user_ldap {
//  username = "my_tf_user_ldap_${random_string.user_suffix.result}"
//  user_type = "LDAP"
//  first_name = "my"
//  last_name = "tf user ldap"
//  password = var.user_resource_password
//}
```

## Debug Output
```bash
# updating usertype attribute

│ Error: {"$objectType":"iam.v4.authn.UpdateUserApiResponse","$reserved":{"$fv":"v4.r0"},"$dataItemDiscriminator":"iam.v4.error.ErrorResponse","data":{"$objectType":"iam.v4.error.ErrorResponse","$reserved":{"$fv":"v4.r0"},"$errorItemDiscriminator":"List\u003ciam.v4.error.AppMessage\u003e","error":[{"$objectType":"iam.v4.error.AppMessage","$reserved":{"$fv":"v4.r0"},"argumentsMap":{"operation":"update user"},"code":"IAM-21408","errorGroup":"IAM-AUTHN-USER-VAL-ERR","locale":"en_US","message":"Failed to update user as the user type cannot be modified.","severity":"ERROR"}]}}
```

## Expected Behaviour
- Provider should be able to handle CRUDI operations.
- Attributes/Arguments have proper validation mechanism's so that runtime issues can be avoided (ie the provider fails midway and outputs raw api errors)
- Proper recreation mechanism's for when the resource cannot be updated in place.
- The resource name should be **"user"** and not **"users"**

## Actual Behaviour
- Update is broken since the [Update user operation](https://developers.nutanix.com/api-reference?namespace=iam&version=v4.0#tag/Users/operation/updateUserById) sometimes makes the **emailId** attribute required and the [Create user operation](https://developers.nutanix.com/api-reference?namespace=iam&version=v4.0#tag/Users/operation/createUser) does not require the same attribute.
- Another issue with Update operations is that modification of certain attributes does not trigger a replacement of the resource (ie the api does not allow certain attributes to be modified) and since the schema is incorrectly set for the resource this behaviour is not taken into account for. The **usertype** attribute for example.
- Delete is broken since there is no **Delete User operation** in the v4 API. This could be implemented with the [v3 API operation](https://www.nutanix.dev/api_reference/apis/prism_v3.html#tag/users/paths/~1users~1%7Buuid%7D/delete)
- The provider fails with a raw API responses, due to that the resource schema validation is missing or incorrect.
- Schema validation will be hard since the different usertype has different other required attributes. I suggest splitting the user resource either in the Provider or the v4 api into multiple resources. An example of a similar solution is the AWS Provider resources [aws_iam_user](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user) and [aws_cognito_user](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user)
- User password is exposed in state

#### Create
⚠️ Create
User type validation needs work, or splitting into multiple resources.

#### Read
✔️ 
Seems Okay

#### Update
⚠️
Broken since gap of required attributes between Create and Update API's in v4

#### Delete
❌
Not implemented in v4, could use v3 until the api operation is implemented

#### Import
✔️
Seems okay

## Steps To Reproduce
1. Create main.tf and define a resource
2. Issue `terraform apply` - **Create** is tested
3. Modify a computed attribute on the resurce via the api or the webui and issue `terraform refresh` - **Read** is tested
4. Modify an attribute in main.tf and run `terraform apply` - **Update** is tested
5. Issue terraform destroy - **Delete** is tested
6. Issue `terraform apply`, then `terraform state rm <resource_address>`, then `terraform import <resource_address> <resource_id>` - **Import** is tested

## Important Factors

### PR DESCRIPTION
**Pull request by Haroon-Dweikat-Ntx**
This BR include : 

- fix "" string issue for MiddleInitial,  EmailId and DisplayName
- add validation on status

### CODE REVIEW

**Comment by Haroon-Dweikat-Ntx** [comment]
/ok-to-test TestAccV2NutanixUser*
- 🧪 **`Build Status: `** `success`
- 📌 **`GitHub Action: `** [View GitHub Actions Run](https://github.com/nutanix/terraform-provider-nutanix/actions/runs/16641646469)
- 📊 **`Code Coverage: `** `Current line coverage (2.5) is below threshold (50). Kindly add more acceptance tests.`
- 📝 **`Test Summary: `**
```txt
==================================================🧪 TEST SUMMARY 🧪=================================================================================
Total Test Cases Run 🚀: 30
Total Test Cases Passed ✅: 29 (96 %)
Total Test Cases Failed ❌: 0 (0 %)
Total Test Cases Skipped ⚠️: 1 (3 %)
==================================================================================================================================================

================================================== TESTS SUCCEEDED ✅ =============================================================================

✅ TestAccV2NutanixUserGroupsDatasource_GetUserGroupByExtId
✅ TestAccV2NutanixUserGroupsDatasource_Basic
✅ TestAccV2NutanixUserGroupsDatasource_WithFilter
✅ TestAccV2NutanixUserGroupsDatasource_WithLimit
✅ TestAccV2NutanixUserGroupsDatasource_WithInvalidFilter
✅ TestAccV2NutanixUsersDataSourceKey
✅ TestAccV2NutanixUsersDataSourceKeyInvalid
✅ TestAccV2NutanixUsersDataSourceKeys
✅ TestAccV2NutanixUserDatasource_Basic
✅ TestAccV2NutanixUserDatasourceServiceAccount
✅ TestAccV2NutanixUsersDatasource_Basic
✅ TestAccV2NutanixUsersDatasource_WithFilter
✅ TestAccV2NutanixUsersDatasource_WithLimit
✅ TestAccV2NutanixUsersDatasource_WithInvalidFilter
✅ TestAccV2NutanixUsersDataSourceServiceAccount
✅ TestAccV2NutanixUserGroupsResource_LDAPUserGroup
✅ TestAccV2NutanixUserGroupsResource_SAMLUserGroup
✅ TestAccV2NutanixUserGroupsResource_WithNoGroupType
✅ TestAccV2NutanixUserGroupsResource_WithNoIdpId
✅ TestAccV2NutanixUsers_CreateKey
✅ TestAccV2NutanixUsers_CreateKey_DuplicateName
✅ TestAccV2NutanixUsersRevokeKey
✅ TestAccV2NutanixUsersResource_LocalActiveUser
✅ TestAccV2NutanixUsersResource_AlreadyExistsUser
✅ TestAccV2NutanixUsersResource_LocalInactiveUser
✅ TestAccV2NutanixUsersResource_SAMLUser
✅ TestAccV2NutanixUsersResource_LDAPUser
✅ TestAccV2NutanixUsersResource_WithNoUserName
✅ TestAccV2NutanixUsersResource_WithNoUserType
===================================================================================================================================================

================================================== TESTS FAILED ❌ ================================================================================
🎉💃 No tests failed 🕺🎉
===================================================================================================================================================

================================================== TESTS SKIPPED ⚠️ ==============================================================================
⚠️ TestAccV2NutanixUsersResource_DeactivateLocalUser   : Reason: ➡️ :      resource_nutanix_users_v2_test.go:163: these test were commented since they are using different APIs
===================================================================================================================================================

```

**Comment by Haroon-Dweikat-Ntx** [comment]
/ok-to-test TestAccV2NutanixUser*


- 🧪 **`Build Status: `** `success`
- 📌 **`GitHub Action: `** [View GitHub Actions Run](https://github.com/nutanix/terraform-provider-nutanix/actions/runs/16642803298)
- 📊 **`Code Coverage: `** `Current line coverage (2.5) is below threshold (50). Kindly add more acceptance tests.`
- 📝 **`Test Summary: `**
```txt
==================================================🧪 TEST SUMMARY 🧪=================================================================================
Total Test Cases Run 🚀: 31
Total Test Cases Passed ✅: 30 (96 %)
Total Test Cases Failed ❌: 0 (0 %)
Total Test Cases Skipped ⚠️: 1 (3 %)
==================================================================================================================================================

================================================== TESTS SUCCEEDED ✅ =============================================================================

✅ TestAccV2NutanixUserGroupsDatasource_GetUserGroupByExtId
✅ TestAccV2NutanixUserGroupsDatasource_Basic
✅ TestAccV2NutanixUserGroupsDatasource_WithFilter
✅ TestAccV2NutanixUserGroupsDatasource_WithLimit
✅ TestAccV2NutanixUserGroupsDatasource_WithInvalidFilter
✅ TestAccV2NutanixUsersDataSourceKey
✅ TestAccV2NutanixUsersDataSourceKeyInvalid
✅ TestAccV2NutanixUsersDataSourceKeys
✅ TestAccV2NutanixUserDatasource_Basic
✅ TestAccV2NutanixUserDatasourceServiceAccount
✅ TestAccV2NutanixUsersDatasource_Basic
✅ TestAccV2NutanixUsersDatasource_WithFilter
✅ TestAccV2NutanixUsersDatasource_WithLimit
✅ TestAccV2NutanixUsersDatasource_WithInvalidFilter
✅ TestAccV2NutanixUsersDataSourceServiceAccount
✅ TestAccV2NutanixUserGroupsResource_LDAPUserGroup
✅ TestAccV2NutanixUserGroupsResource_SAMLUserGroup
✅ TestAccV2NutanixUserGroupsResource_WithNoGroupType
✅ TestAccV2NutanixUserGroupsResource_WithNoIdpId
✅ TestAccV2NutanixUsers_CreateKey
✅ TestAccV2NutanixUsers_CreateKey_DuplicateName
✅ TestAccV2NutanixUsersRevokeKey
✅ TestAccV2NutanixUsersResource_LocalActiveUser
✅ TestAccV2NutanixUsersResource_AlreadyExistsUser
✅ TestAccV2NutanixUsersResource_LocalActiveUserMiniConfig
✅ TestAccV2NutanixUsersResource_LocalInactiveUser
✅ TestAccV2NutanixUsersResource_SAMLUser
✅ TestAccV2NutanixUsersResource_LDAPUser
✅ TestAccV2NutanixUsersResource_WithNoUserName
✅ TestAccV2NutanixUsersResource_WithNoUserType
===================================================================================================================================================

================================================== TESTS FAILED ❌ ================================================================================
🎉💃 No tests failed 🕺🎉
===================================================================================================================================================

================================================== TESTS SKIPPED ⚠️ ==============================================================================
⚠️ TestAccV2NutanixUsersResource_DeactivateLocalUser   : Reason: ➡️ :      resource_nutanix_users_v2_test.go:198: these test were commented since they are using different APIs
===================================================================================================================================================

```

File: nutanix/services/iamv2/resource_nutanix_users_v2.go [hunk 1]
```diff
@@ -392,6 +396,20 @@ func resourceNutanixUserV2Update(ctx context.Context, d *schema.ResourceData, me
 
 	updateSpec = &getUserResp
 
+	// validation on update spec
+	// Note: user read response has "" as default value for  middleInitial, emailId,
+	if updateSpec.MiddleInitial != nil && utils.StringValue(updateSpec.MiddleInitial) == "" {
```
Comment (GullapalliAkhil) [inline nutanix/services/iamv2/resource_nutanix_users_v2.go:401]: This'll be always False?

Comment (Haroon-Dweikat-Ntx) [reply nutanix/services/iamv2/resource_nutanix_users_v2.go:401]: No, it will be True if the MiddleInitial is not set in create context, which will be "" as default,  we  assign nil when its "" because we can not set these attributes as "", there is a validation at API level

**Review by GullapalliAkhil — APPROVED** [review]
