### PR TITLE
Fix nutanix_virtual_machine_v2 cannot read guest customization config for windows 

### LINKED ISSUE #791: nutanix_virtual_machine_v2 cannot read guest customization config for windows
### Nutanix Cluster Information
 - Nutanix Prism Central - Version pc.2024.3.0.1

### Terraform Version
Terraform v1.11.2

### Affected Resource(s)

* nutanix_virtual_machine_v2
### Terraform Configuration Files

```hcl
  guest_customization {
    config {
      sysprep {
        install_type = "PREPARED"
        sysprep_script {
          unattend_xml {
                value = base64encode("${element(data.template_file.init_web_vm.*.rendered, 0)}")
          }
        }
      }
    }
  }
```

### Actual Behavior

Error when running terraform apply, nutanix_virtual_machine_v2 is not able to read the guest customization data within

│ Error: error waiting for virtual Machine  to create: error_detail: Failed to perform the operation on the VM with UUID '{{{vm_uuid}}}', due to an invalid argument with key 'UnattendXml' and value 'EMPTY'., progress_message: 100
│

### Steps to Reproduce

1. `terraform apply`
### Important Factors

* #0000

### LINKED ISSUE #863: UnattendXml value appears EMPTY in API payload despite correct Terraform plan (Provider v2.2.0)
Problem Description
I'm attempting to provision Windows virtual machines on a Nutanix AHV cluster using the nutanix_virtual_machine_v2 resource with guest_customization and a Sysprep unattend.xml file.

The expected behavior is that the VM should be created and successfully customized by Sysprep using the provided unattend.xml content.

However, when executing terraform apply, the VM creation fails with an error indicating an invalid argument for UnattendXml, specifically stating value: 'EMPTY'.

Steps to Reproduce
Terraform Configuration (main.tf - simplified):

Terraform

resource "nutanix_virtual_machine_v2" "example_vm" {
  name        = var.hostname
  cluster_uuid = var.cluster_uuid
  num_sockets = var.cpu_sockets
  num_vcpus_per_socket = var.cpu_cores
  memory_mb   = var.memory_gb * 1024
  image_uuid  = var.image_uuid

  nic_list {
    subnet_uuid = var.subnet_uuid
    ip_endpoint_list {
      ip = var.ip_address
    }
  }

  guest_customization {
    config {
      dynamic "sysprep" {
        for_each = var.os_type == "windows" ? [1] : []
        content {
          install_type = "PREPARED"
          sysprep_script {
            unattend_xml {
              value = base64encode(templatefile(var.sysprep_template, {
                hostname    = var.hostname
                vm_password = var.vm_password
                ip_address  = var.ip_address
                netmask     = var.netmask
                gateway     = var.gateway
                dns1        = var.dns1
                dns2        = var.dns2
              }))
            }
          }
        }
      }
    }
  }
}

Execution Steps:

terraform init
terraform plan (observing the correct Base64 output for unattend_xml.value)
TF_LOG=TRACE terraform apply
Expected vs. Actual Results
Expected: The VM is created, and the unattend.xml (containing substituted variables) is successfully passed to Nutanix, resulting in the VM being customized (e.g., hostname set, password changed).

Actual: The terraform apply fails with an error similar to this:

Error: Failed to create Virtual Machine: [Error details]
error_detail: Failed to perform the operation on the VM with UUID '[VM_UUID]', due to an invalid argument with key 'UnattendXml' and value 'EMPTY'
Evidence from Debugging
terraform plan output: When running terraform plan, the unattend_xml.value attribute correctly shows a populated Base64 string. This confirms that Terraform is correctly reading the sysprep.xml and performing the templatefile and base64encode operations as expected.
+ guest_customization {
...
        + unattend_xml {
              + value = "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPgo8dW5hdHRlbmQgeG1sbnM9InVybj... (full base64 string here)"
        }
...
}
TF_LOG=TRACE output: When inspecting the Vm Create Request Payload in the TF_LOG=TRACE output, the sysprepScript.Unattendxml object appears as empty ({}). This indicates that despite Terraform preparing the Base64 value, the provider is not including it in the final JSON payload sent to the Nutanix API.
JSON

"guestCustomization": {
  "config": {
    "sysprepScript": {
      "$objectType": "vmm.v4.ahv.config.Unattendxml",
      "$reserved": {
        "$fv": "v4.r0"
      }
    } // <-- This Unattendxml object is empty, missing the 'value' field.
  }
},

The sysprep.xml content itself is valid.
The Windows image is capable of being Sysprepped.
The Nutanix cluster's guest customization functionality is working as expected.
This issue appears to be specific to how the nutanix/nutanix Terraform provider (v2.2.0) is handling the unattend_xml.value attribute when constructing the API request. I've noted a commit ([88427b3cebbab726dada4b7e65f0a4550785755b](https://www.google.com/search?q=%5Bhttps://github.com/nutanix/terraform-provider-nutanix/commit/88427b3cebbab726dada4b7e65f0a4550785755b%5D(https://github.com/nutanix/terraform-provider-nutanix/commit/88427b3cebbab726dada4b7e65f0a4550785755b))) that seems to address a similar issue ("unable to read guest customization configurations, specifically for Windows"), but the problem persists in the latest available provider version.

### PR DESCRIPTION
**Pull request by Haroon-Dweikat-Ntx**
Fix issue #791: 
- Ensure the correct `sysprep_script` value is read while expanding the provided configuration and preparing the VM create payload

### CODE REVIEW

**Comment by Haroon-Dweikat-Ntx** [comment]
/ok-to-test TestAccV2NutanixVms*
> Acceptance test run status: success
> **📌 [View GitHub Actions Run](https://github.com/nutanix/terraform-provider-nutanix/actions/runs/14489325688)**
> Current line coverage (7.3) is below threshold (50). Kindly add more acceptance tests.

**Comment by Haroon-Dweikat-Ntx** [comment]
/ok-to-test TestAccV2NutanixVmsShutdownResource_Basic


> Acceptance test run status: success
> **📌 [View GitHub Actions Run](https://github.com/nutanix/terraform-provider-nutanix/actions/runs/14495166094)**
> Current line coverage (3.9) is below threshold (50). Kindly add more acceptance tests.

**Comment by Haroon-Dweikat-Ntx** [comment]
Tests Passed: 
```
==================================================🧪 TEST SUMMARY 🧪=================================================================================
Total Test Cases Run 🐹🚀: 36
Total Test Cases Passed 🐹✅: 32 (88 %)
Total Test Cases Failed 🐹❌: 1 (2 %)
Total Test Cases Skipped 🐹⚠️: 3 (8 %)
==================================================================================================================================================
================================================== TESTS SUCCEEDED ✅ =============================================================================

✅ TestAccV2NutanixVmRecoveryPointDatasource_VmRecoveryPoint
✅ TestAccV2NutanixVmsDatasource_Basic
✅ TestAccV2NutanixVmsDatasource_WithConfig
✅ TestAccV2NutanixVmsDatasource_WithCdromConfig
✅ TestAccV2NutanixVmsDatasource_WithCdromBackingInfo
✅ TestAccV2NutanixVmsDatasource_List
✅ TestAccV2NutanixVmsDatasource_ListWithFilters
✅ TestAccV2NutanixVmsDatasource_ListWithFilterName
✅ TestAccV2NutanixVmsResource_Basic
✅ TestAccV2NutanixVmsResource_BasicUpdate
✅ TestAccV2NutanixVmsResource_WithDisk
✅ TestAccV2NutanixVmsResource_DiskWithDatasource
✅ TestAccV2NutanixVmsResource_WithNic
✅ TestAccV2NutanixVmsResource_WithNicTrunk
✅ TestAccV2NutanixVmsResource_WithLegacyBootOrder
✅ TestAccV2NutanixVmsResource_WithUEFIBootOrder
✅ TestAccV2NutanixVmsResource_WithCdrom
✅ TestAccV2NutanixVmsResource_WithCdromIDE
✅ TestAccV2NutanixVmsResource_WithCdromBackingInfo
✅ TestAccV2NutanixVmsResource_WithCloudInit
✅ TestAccV2NutanixVmsResource_UpdateDiskNics
✅ TestAccV2NutanixVmsResource_WithLegacyBootDevice
✅ TestAccV2NutanixVmsResource_WithCategories
✅ TestAccV2NutanixVmsResource_WithSerialPorts
✅ TestAccV2NutanixVmsCdromInsertEjectResource_Basic
✅ TestAccV2NutanixVmsCloneResource_Basic
✅ TestAccV2NutanixVmsCloneResource_WithGuestCustomization
✅ TestAccV2NutanixVmsCloneResource_WithUefiBootConfig
✅ TestAccV2NutanixVmsGCUpdateResource_Basic
✅ TestAccV2NutanixVmsNetworkDeviceAssignIpResource_Basic
✅ TestAccV2NutanixVmsNetworkDeviceMigrateResource_Basic
✅ TestAccV2NutanixVmsShutdownResource_WithError
===================================================================================================================================================
================================================== TESTS FAILED ❌ ================================================================================

❌ TestAccV2NutanixVmsShutdownResource_Basic
===================================================================================================================================================
================================================== TESTS SKIPPED ⚠️ ==============================================================================
⚠️ TestAccV2NutanixVmRecoveryPointDatasource_VmRecoveryPointWithAppConsProps   : Reason: ➡️ :      data_source_nutanix_vm_recovery_point_info_v2_test.go:43: Skipping this test case as it is failing due to missing app consistent properties in get request
⚠️ TestAccV2NutanixVmsResource_WithCloudInitWithCustomKeys   : Reason: ➡️ :      resource_nutanix_virtual_machine_v2_test.go:435: Failing due to issue with cloud_init user_data & custom_keys
⚠️ TestAccV2NutanixVmsResource_WithGpus   : Reason: ➡️ :      resource_nutanix_virtual_machine_v2_test.go:644: Skipping test as no GPU devices found
===================================================================================================================================================

```

**Comment by Haroon-Dweikat-Ntx** [comment]
Test Pass : 
```
==================================================🧪 TEST SUMMARY 🧪=================================================================================
Total Test Cases Run 🐹🚀: 1
Total Test Cases Passed 🐹✅: 1 (1*** %)
Total Test Cases Failed 🐹❌: ***
*** ( %)
Total Test Cases Skipped 🐹⚠️: ***
*** ( %)
==================================================================================================================================================
================================================== TESTS SUCCEEDED ✅ =============================================================================

✅ TestAccV2NutanixVmsShutdownResource_Basic
===================================================================================================================================================
================================================== TESTS FAILED ❌ ================================================================================
===================================================================================================================================================
================================================== TESTS SKIPPED ⚠️ ==============================================================================
===================================================================================================================================================

```

**Comment by Haroon-Dweikat-Ntx** [comment]
/ok-to-test TestAccV2NutanixVmsResource_WithSysprep
> Acceptance test run status: success
> **📌 [View GitHub Actions Run](https://github.com/nutanix/terraform-provider-nutanix/actions/runs/14512314857)**
> Current line coverage (2.8) is below threshold (50). Kindly add more acceptance tests.

**Comment by Haroon-Dweikat-Ntx** [comment]
Test Pass : 
```
==================================================🧪 TEST SUMMARY 🧪=================================================================================
Total Test Cases Run 🐹🚀: 1
Total Test Cases Passed 🐹✅: 1 (1*** %)
Total Test Cases Failed 🐹❌: ***
*** ( %)
Total Test Cases Skipped 🐹⚠️: ***
*** ( %)
==================================================================================================================================================
================================================== TESTS SUCCEEDED ✅ =============================================================================
✅ TestAccV2NutanixVmsResource_WithSysprep
===================================================================================================================================================
================================================== TESTS FAILED ❌ ================================================================================
===================================================================================================================================================
================================================== TESTS SKIPPED ⚠️ ==============================================================================
===================================================================================================================================================
```

File: nutanix/services/vmmv2/resource_nutanix_virtual_machine_v2_test.go [hunk 1]
```diff
@@ -1382,6 +1409,82 @@ func testVmsV4ConfigWithCloudInit(r int, desc string) string {
...
+func testVmsV4ConfigWithSysprep(r int, desc string) string {
+	return fmt.Sprintf(`
+data "nutanix_clusters_v2" "clusters" {}
+
+locals {
+	cluster0 = [
+	for cluster in data.nutanix_clusters_v2.clusters.cluster_entities :
+	cluster.ext_id if cluster.config[0].cluster_function[0] != "PRISM_CENTRAL"
+	][0]
+	gs = base64encode("#cloud-config\nusers:\n  - name: ubuntu\n    ssh-authorized-keys:\n      - ssh-rsa DUMMYSSH mypass\n    sudo: ['ALL=(ALL) NOPASSWD:ALL']")
```
Comment (bhati-pradeep) [inline nutanix/services/vmmv2/resource_nutanix_virtual_machine_v2_test.go]: Why do we need this ?

Comment (bhati-pradeep) [reply nutanix/services/vmmv2/resource_nutanix_virtual_machine_v2_test.go]: Remove if not required

File: website/docs/r/virtual_machine_v2.html.markdown [hunk 2]
```diff
@@ -189,6 +190,7 @@ The `guest_customization` attribute supports the following:
 * `metadata`: The contents of the meta_data configuration for cloud-init. This can be formatted as YAML or JSON. The value must be base64 encoded. Default value is 'CONFIG_DRIVE_V2'.
 * `cloud_init_script`: (Optional) The script to use for cloud-init.
 * `cloud_init_script.user_data`: (Optional) user data object
+* `cloud_init_script.user_data.value`: (Optional) user data object base64 encoded value
```
Comment (bhati-pradeep) [inline website/docs/r/virtual_machine_v2.html.markdown]:
```suggestion
* `cloud_init_script.user_data.value`: (Optional) base64 encoded cloud init script as string
```

File: website/docs/r/virtual_machine_v2.html.markdown [hunk 3]
```diff
@@ -181,6 +181,7 @@ The `guest_customization` attribute supports the following:
 * `install_type`: (Optional) Indicates whether the guest will be freshly installed using this unattend configuration, or this unattend configuration will be applied to a pre-prepared image. Values allowed is 'PREPARED', 'FRESH'.
 * `sysprep_script`: (Optional) Object either UnattendXml or CustomKeyValues
 * `sysprep_script.unattend_xml`: (Optional) xml object
+* `sysprep_script.unattend_xml.value`: (Optional) xml object base64 encoded value
```
Comment (bhati-pradeep) [inline website/docs/r/virtual_machine_v2.html.markdown]:
```suggestion
* `sysprep_script.unattend_xml.value`: (Optional) base64 encoded sysprep unattended xml```

**Review by bhati-pradeep — CHANGES_REQUESTED** [review]
Can you please add one example in examples/ section ?

File: nutanix/services/vmmv2/resource_nutanix_virtual_machine_v2_test.go (hunk 1 above)
Comment (Haroon-Dweikat-Ntx) [reply nutanix/services/vmmv2/resource_nutanix_virtual_machine_v2_test.go]: removed

File: website/docs/r/virtual_machine_v2.html.markdown (hunk 2 above)
Comment (Haroon-Dweikat-Ntx) [reply website/docs/r/virtual_machine_v2.html.markdown]: attribute description updated

File: website/docs/r/virtual_machine_v2.html.markdown (hunk 3 above)
Comment (Haroon-Dweikat-Ntx) [reply website/docs/r/virtual_machine_v2.html.markdown]: attribute description updated

**Review by bhati-pradeep — APPROVED** [review]
LGTM

File: nutanix/services/vmmv2/resource_nutanix_virtual_machine_v2.go [hunk 4]
```diff
@@ -1432,10 +1432,11 @@ func schemaForGuestCustomization() *schema.Schema {
 														Computed: true,
 														Elem: &schema.Resource{
 															Schema: map[string]*schema.Schema{
+																// this value is required but not present in API reference
+																// the create vm request fails if this is not provided or is empty
 																"value": {
 																	Type:     schema.TypeString,
```
Comment (GullapalliAkhil) [inline nutanix/services/vmmv2/resource_nutanix_virtual_machine_v2.go:1438]: Why we miss this in our testing?

**Review by GullapalliAkhil — APPROVED** [review]
LGTM!
