### PR TITLE
fix validation for access control policy

### LINKED ISSUE #688: nutanix_access_control_policy unable to be applied due to scope validation.
### Nutanix Cluster Information
Nutanix Cluster 6.8.1
Prism Central 2024.1.0.2

### Terraform Version
```
Terraform v1.9.5
on linux_amd64
+ provider registry.terraform.io/nutanix/nutanix v1.2.0
```

### Affected Resource(s)
nutanix_access_control_policy

### Terraform Configuration Files

```hcl
    context_filter_list {
        entity_filter_expression_list {
            left_hand_side_entity_type = "all"
            operator                   = "IN"

            right_hand_side {
                collection = "ALL"
                uuid_list  = []
            }
        }
        scope_filter_expression_list {
            left_hand_side = "CLUSTER"
            operator       = "IN"

            right_hand_side {
                collection = "ALL"
                uuid_list  = []
            }
        }
    }
```
### Expected Behavior
This is from a import of a ACP that gives permissions across all clusters. 

### Actual Behavior
Running terraform plan results in an error:
```
expected context_filter_list.1.scope_filter_expression_list.0.left_hand_side to be one of [CATEGORY PROJECT], got CLUSTER
```

If we change CLUSTER to CATEGORY terraform plan completes, but terraform apply gives this error:
```
 Error: error updating access control policy id 54ed7fe3-7316-4491-9a4e-9176c46be14a): error: {
   "api_version": "3.1",
   "code": 422,
   "message_list": [
     {
       "message": "Validation error. Incorrect filters : Only CLUSTER in Scope allowed with this role.",
       "reason": "VALIDATION_ERROR"
     }
   ],
   "state": "ERROR"
 }
 
   with nutanix_access_control_policy.prism_viewer_01,
   on main.tf line 90, in resource "nutanix_access_control_policy" "prism_viewer_01":
   90: resource "nutanix_access_control_policy" "prism_viewer_01" {
```

### Steps to Reproduce

1. Import or create ACP for Prism Admin or Prism Viewer role with cluster scope.
2. `terraform plan`
3. Change CLUSTER to CATEGORY or PROJECT as directed.
4. `terraform plan`
5. `terraform apply`

​

### PR DESCRIPTION
**Pull request by Haroon-Dweikat-Ntx**
fix validation for access control policy, add ["CLUSTER", "VPC", "CONNECTIVITY_TYPE"] as accepted values for context_filter_list.scope_filter_expression_list.left_hand_side attribute

### CODE REVIEW

**Comment by Haroon-Dweikat-Ntx** [comment]
/ok-to-test TestAccNutanixAccessControlPolicy_
> Acceptance test run status: success
> **📌 [View GitHub Actions Run](https://github.com/nutanix/terraform-provider-nutanix/actions/runs/15271082420)**
> Current line coverage (1.1) is below threshold (50). Kindly add more acceptance tests.

**Comment by Haroon-Dweikat-Ntx** [comment]
/ok-to-test TestAccNutanixAccessControlPolicy_


> Acceptance test run status: success
> **📌 [View GitHub Actions Run](https://github.com/nutanix/terraform-provider-nutanix/actions/runs/15271547423)**
> Current line coverage (1.8) is below threshold (50). Kindly add more acceptance tests.

**Comment by Haroon-Dweikat-Ntx** [comment]
Log: 
```
==================================================================================================================================================
================================================== TESTS SUCCEEDED ✅ =============================================================================
✅ TestAccNutanixAccessControlPolicy_WithUser
✅ TestAccNutanixAccessControlPolicy_WithCluster
✅ TestAccNutanixAccessControlPolicy_WithVPC
✅ TestAccNutanixAccessControlPolicy_WithConnectivityType
===================================================================================================================================================
================================================== TESTS FAILED ❌ ================================================================================
===================================================================================================================================================
================================================== TESTS SKIPPED ⚠️ ==============================================================================
⚠️ TestAccNutanixAccessControlPolicy_basic   : Reason: ➡️ :      resource_nutanix_access_control_policy_test.go:2***: 
⚠️ TestAccNutanixAccessControlPolicy_WithCategory   : Reason: ➡️ :      resource_nutanix_access_control_policy_test.go:95: 
===================================================================================================================================================

```

File: nutanix/services/prism/resource_nutanix_access_control_policy.go [hunk 1]
```diff
@@ -165,7 +165,7 @@ func ResourceNutanixAccessControlPolicy() *schema.Resource {
 									"left_hand_side": {
 										Type:         schema.TypeString,
 										Required:     true,
-										ValidateFunc: validation.StringInSlice([]string{"CATEGORY", "PROJECT"}, false),
+										ValidateFunc: validation.StringInSlice([]string{"CATEGORY", "PROJECT", "CLUSTER", "VPC", "CONNECTIVITY_TYPE"}, false),
```
Comment (GullapalliAkhil) [inline nutanix/services/prism/resource_nutanix_access_control_policy.go:168]: Can you share the API reference for this to cross check?

Comment (Haroon-Dweikat-Ntx) [reply nutanix/services/prism/resource_nutanix_access_control_policy.go:168]: spec -> resources -> filter_list -> context_list -> scope_filter_expression_list -> left_hand_side
https://www.nutanix.dev/api_reference/apis/prism_v3.html#tag/access_control_policies/paths/~1access_control_policies/post:~:text=an%20scope%20expression.-,left_hand_side,-required

**Review by GullapalliAkhil — APPROVED** [review]
